# Classifying IMDB Movie Reviews with BERT Transformers

- [View Solution Notebook](./solutions.html)
- [View Project Page](https://www.codecademy.com/content-items/29838c7636654e48ac72458af6373d5d)

**Setup - Import Libraries**

Run the cell below to import the libraries and set the random seed.

In [1]:
# %pip install transformers
# %pip install datasets

In [2]:
import numpy as np
import pandas as pd
from datasets import load_dataset

import torch
torch.manual_seed(42) # set random seed --do not change!

from transformers import logging
logging.set_verbosity_error() # remove warnings --do not change!

[transformers] Disabling PyTorch because PyTorch >= 2.6 is required but found 2.5.1
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

## Task Group 1 - Import and Inspect the Movie Reviews

Let's first import and inspect the datasets containing the movie reviews!

### Task 1

In this project, we'll be classifying different _aspects_ within movie reviews from IMDB (Internet Movie Database), which is a free online database containing data on movies, TV shows, and other types of media.

We've obtained the movie reviews from this [Hugging Face Dataset](https://huggingface.co/datasets/Lowerated/lm6-movies-reviews-aspects) that we've cleaned and pre-processed into the following files:
- `"datasets/imdb_movie_reviews_train.csv"` - contains movie reviews in the training dataset
- `"datasets/imdb_movie_reviews_test.csv"` - contains the movie reviews in the testing dataset

Here's a quick summary of the columns in the dataset:

- `review` - the text of the movie review
- `aspect` - the thematic aspect of the movie the review targets
- `aspect_encoded` an integer label encoding the `aspect` column

Start by importing the CSV file to a pandas DataFrame named `train_reviews_df`.

Use the `.head()` method to preview the first five rows.

In [59]:
training_ds = pd.read_csv("data/imdb_movie_reviews_train.csv", sep=",")

In [60]:
training_ds.head()

,review,aspect,aspect_encoded
0,Ibiza filming location looks very enchanting,Cinematography,0
1,RANDOLPH SCOTT always played men you could loo...,Characters,1
2,"interesting and promising basic idea', 'some p...",Story,2
3,"the film could explore very powerful politics,...",Story,2
4,"The animation is nice, and the use of color ma...",Cinematography,0

### Task 2

Next, use `.info()` to inspect the training dataset. Make sure the data types for each column make sense and if there are any missing values.

In [61]:
training_ds.shape

(369, 3)

In [62]:
training_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review          369 non-null    object
 1   aspect          369 non-null    object
 2   aspect_encoded  369 non-null    int64
dtypes: int64(1), object(2)
memory usage: 8.8+ KB

### Task 3

Let's explore the different aspect labels in the training dataset.

Use the `.value_counts()` method on the `aspect` column to count the number of aspect labels.

Do the same for the `aspect_encoded` column to verify that the number of aspect labels correspond equally.

In [63]:
training_ds.isna().mean() * 100

review            0.0
aspect            0.0
aspect_encoded    0.0
dtype: float64

In [64]:
training_ds.value_counts("aspect")

aspect
Cinematography    125
Characters        123
Story             121
Name: count, dtype: int64

In [65]:
training_ds.value_counts("aspect_encoded")

aspect_encoded
0    125
1    123
2    121
Name: count, dtype: int64

Here's a quick summary of each aspect:

- **Cinematography** focuses on the movie's visual elements like the locations, quality, lighting, and visual appeal
- **Characters** addresses the portrayal of characters and their development throughout the movie, which can focus on their acting, personality, depth, and relatability
- **Story** highlights the movie's themes, plots, originality, and quality of storytelling

### Task 4

Since each movie review is classified into one of the three aspects, we'll frame this task as a **multi-class** classification task. 

Let's save the number of aspects to the variable `n_aspects`, which we'll reference later when we build the neural network and BERT transformer using PyTorch.

In [66]:
n_aspects = training_ds["aspect"].nunique()
n_aspects

3

### Task 5

Next, create the _training corpus_ by using the `.tolist()` function to convert the text sequence in each review and their corresponding aspect labels to the following lists:

- `train_texts` contains each movie review separated by commas
- `train_labels` contains each review aspect separated by commas

In [67]:
train_texts = training_ds["review"].to_list()
train_labels = training_ds["aspect_encoded"].to_list()

In [68]:
len(train_texts)

369

In [69]:
len(train_labels)

369

## Task Group 2 - Pre-processing the Text Data

Next, we'll need to pre-process the text data into a numerical representation that our text classification model will understand!

### Task 6

Next, let's tokenize each review into word tokens.

A. Create a function named `tokenize_review` that uses each review text as input.
- with the `re` module, use the `re.findall()` function to lowercase the text using `.lower()` and locate words (without punctuations and special characters) using the regular expression `r'\b\w+\b'`
- save the tokenized text to the variable `tokenized_review_text` within the function
- make sure the function returns the tokenized text

B. Apply the function to tokenize each review text in the training corpus.
- use a `for` loop to apply the `tokenize` function to each review text in `train_texts`
- save the list of tokenized reviews to the variable `tokenized_corpus`

In [70]:
import re
def tokenize_review(text):
    tokenized_review_text = re.findall(r'\b\w+\b', text.lower())
    return tokenized_review_text

tokenized_corpus = [tokenize_review(review_text) for review_text in train_texts]

In [71]:
# tokenized_corpus

### Task 7

From the `collections` module, use the `Counter()` function to count the number of occurrences of each token and save the counts to the variable `word_freqs`
- First, we'll need to combine each tokenized text sequence together into a single, long list of tokens of the full training corpus. We'll save the list to the variable `combined_corpus`.
- Next, you'll need to create a _nested loop_ that first loops through each tokenized text sequence within the training corpus
- Then, the second loop iterates through each token within each text sequence and appends each token to `combined_corpus`
- Lastly, apply the `Counter()` function to `combined_corpus` to count the number of occurrences of each token

In [72]:
combined_corpus = [ item for sublist in tokenized_corpus for item in sublist]

In [73]:
len(combined_corpus)

10746

In [74]:
from collections import Counter

word_freq = Counter(combined_corpus)
# print(word_freq)

### Task 8

Use the `.most_common()` function to obtain the top 1000 most commonly occurring tokens.
- Set the value `1000` to the variable `MAX_VOCAB_SIZE`
- Save the top 1000 most commonly occurring tokens to the variable `most_common_words`

Print out the top 10 most common words in the training corpus.

In [75]:
MAX_VOCAB_SIZE = 1000
most_common_words = word_freq.most_common(MAX_VOCAB_SIZE)

In [76]:
most_common_words[:10]

[('the', 732),
 ('a', 307),
 ('and', 306),
 ('of', 296),
 ('is', 218),
 ('to', 213),
 ('in', 177),
 ('it', 134),
 ('s', 109),
 ('that', 105)]

### Task 9

Create the vocabulary as a dictionary using the top 1000 most commonly occurring word tokens.
- use the `enumerate` function to assign token IDs for each word token in `most_common_words` based on its positional value **starting at the value 2**
- save the vocabulary to the variable `vocab`

Add the special tokens `<unk>` and `<pad>` to the vocabulary by:
- assigning the special token key `<unk>` with the token ID value `0`
- assigning the special token key `<pad>` with the token ID value `1`

In [77]:
vocab = {word: idx+2 for idx, (word, freq) in enumerate(most_common_words)}

In [78]:
vocab

{'the': 2,
 'a': 3,
 'and': 4,
 'of': 5,
 'is': 6,
 'to': 7,
 'in': 8,
 'it': 9,
 's': 10,
 'that': 11,
 'this': 12,
 'as': 13,
 'i': 14,
 'was': 15,
 'film': 16,
 'for': 17,
 'with': 18,
 'movie': 19,
 'are': 20,
 'his': 21,
 'on': 22,
 'not': 23,
 'they': 24,
 'story': 25,
 'very': 26,
 't': 27,
 'be': 28,
 'he': 29,
 'but': 30,
 'one': 31,
 'all': 32,
 'an': 33,
 'at': 34,
 'some': 35,
 'have': 36,
 'good': 37,
 'characters': 38,
 'you': 39,
 'by': 40,
 'has': 41,
 'like': 42,
 'about': 43,
 'out': 44,
 'or': 45,
 'just': 46,
 'who': 47,
 'there': 48,
 'only': 49,
 'their': 50,
 'her': 51,
 'great': 52,
 'character': 53,
 'more': 54,
 'really': 55,
 'camera': 56,
 'so': 57,
 'also': 58,
 'what': 59,
 'were': 60,
 'can': 61,
 'plot': 62,
 'up': 63,
 'do': 64,
 'into': 65,
 'much': 66,
 'even': 67,
 'work': 68,
 'most': 69,
 'been': 70,
 'best': 71,
 'would': 72,
 'bad': 73,
 'man': 74,
 'from': 75,
 'look': 76,
 'scenes': 77,
 'than': 78,
 'time': 79,
 'acting': 80,
 'its': 81,
 'she': 82,
 'two': 83,
 'way': 84,
 'we': 85,
 'people': 86,
 'other': 87,
 'how': 88,
 'which': 89,
 'too': 90,
 'cinematography': 91,
 'black': 92,
 'could': 93,
 'many': 94,
 'actors': 95,
 'shot': 96,
 'love': 97,
 'interesting': 98,
 'well': 99,
 'him': 100,
 'performance': 101,
 'ever': 102,
 'see': 103,
 'no': 104,
 'made': 105,
 'had': 106,
 'excellent': 107,
 'young': 108,
 'over': 109,
 'first': 110,
 'make': 111,
 'being': 112,
 'any': 113,
 'looks': 114,
 'shots': 115,
 'me': 116,
 'will': 117,
 'when': 118,
 'little': 119,
 'my': 120,
 'guy': 121,
 'girl': 122,
 'here': 123,
 'better': 124,
 'does': 125,
 'find': 126,
 'doesn': 127,
 'seems': 128,
 'effects': 129,
 'off': 130,
 'life': 131,
 'ending': 132,
 'if': 133,
 'white': 134,
 'cast': 135,
 'get': 136,
 'nice': 137,
 'different': 138,
 'world': 139,
 'don': 140,
 'role': 141,
 'rather': 142,
 'lot': 143,
 'beautiful': 144,
 'while': 145,
 'movies': 146,
 'end': 147,
 'feel': 148,
 'job': 149,
 'always': 150,
 'show': 151,
 'between': 152,
 'did': 153,
 'through': 154,
 'where': 155,
 'watch': 156,
 'gets': 157,
 'takes': 158,
 'woman': 159,
 'same': 160,
 'wonderful': 161,
 'short': 162,
 'filmed': 163,
 'know': 164,
 'watching': 165,
 'played': 166,
 'sense': 167,
 'use': 168,
 'scene': 169,
 'them': 170,
 'didn': 171,
 'photography': 172,
 'enough': 173,
 'fun': 174,
 'because': 175,
 'think': 176,
 'long': 177,
 'big': 178,
 'go': 179,
 'real': 180,
 'full': 181,
 'then': 182,
 'script': 183,
 'set': 184,
 'almost': 185,
 'actor': 186,
 'superb': 187,
 'each': 188,
 'drama': 189,
 'around': 190,
 'anything': 191,
 'after': 192,
 'everything': 193,
 'yet': 194,
 'still': 195,
 'plays': 196,
 'past': 197,
 'voice': 198,
 'never': 199,
 'something': 200,
 'women': 201,
 'lighting': 202,
 'especially': 203,
 'why': 204,
 'loved': 205,
 'act': 206,
 'both': 207,
 'town': 208,
 'pretty': 209,
 'lead': 210,
 'idea': 211,
 'us': 212,
 'makes': 213,
 'quite': 214,
 'perfectly': 215,
 'done': 216,
 'awful': 217,
 'series': 218,
 'comedy': 219,
 'poor': 220,
 'fine': 221,
 'john': 222,
 'actually': 223,
 'thought': 224,
 'believe': 225,
 'getting': 226,
 'far': 227,
 'looking': 228,
 'action': 229,
 'lives': 230,
 'audience': 231,
 'true': 232,
 'whole': 233,
 'focus': 234,
 'himself': 235,
 'children': 236,
 'horrible': 237,
 'hard': 238,
 'music': 239,
 'seen': 240,
 'non': 241,
 'funny': 242,
 'performances': 243,
 'richard': 244,
 'quality': 245,
 'new': 246,
 'old': 247,
 'screen': 248,
 'instead': 249,
 'visuals': 250,
 'cave': 251,
 'filming': 252,
 'men': 253,
 'right': 254,
 'thing': 255,
 'robert': 256,
 'color': 257,
 'part': 258,
 'ben': 259,
 'times': 260,
 'years': 261,
 'nothing': 262,
 'jack': 263,
 'original': 264,
 'seemed': 265,
 'boring': 266,
 'kid': 267,
 'impressive': 268,
 'early': 269,
 'dark': 270,
 'own': 271,
 're': 272,
 'hero': 273,
 'entire': 274,
 'shows': 275,
 'dream': 276,
 'got': 277,
 've': 278,
 'm': 279,
 'opening': 280,
 'important': 281,
 'such': 282,
 'face': 283,
 'small': 284,
 'editing': 285,
 'feeling': 286,
 'stunning': 287,
 'style': 288,
 'guys': 289,
 'left': 290,
 'portrayal': 291,
 'wants': 292,
 'angles': 293,
 'works': 294,
 'video': 295,
 'isn': 296,
 'parts': 297,
 'images': 298,
 'bit': 299,
 'half': 300,
 'back': 301,
 'main': 302,
 'making': 303,
 'nearly': 304,
 'another': 305,
 'american': 306,
 'playing': 307,
 'change': 308,
 'couple': 309,
 'middle': 310,
 'relationship': 311,
 'animation': 312,
 'imagery': 313,
 'footage': 314,
 'however': 315,
 'fans': 316,
 'viewer': 317,
 'without': 318,
 'x': 319,
 'seem': 320,
 'constant': 321,
 'stories': 322,
 'given': 323,
 'budget': 324,
 'take': 325,
 'four': 326,
 'effective': 327,
 'create': 328,
 'found': 329,
 'amazing': 330,
 'killing': 331,
 'down': 332,
 'star': 333,
 'clearly': 334,
 'those': 335,
 'emotions': 336,
 'evil': 337,
 'going': 338,
 'war': 339,
 'give': 340,
 'again': 341,
 'although': 342,
 'though': 343,
 'having': 344,
 'murky': 345,
 'scenery': 346,
 'country': 347,
 'visual': 348,
 'book': 349,
 'edie': 350,
 'close': 351,
 'under': 352,
 'turn': 353,
 'things': 354,
 'strong': 355,
 'psychological': 356,
 'horror': 357,
 'certain': 358,
 'entirely': 359,
 'worst': 360,
 'every': 361,
 'these': 362,
 'straight': 363,
 'line': 364,
 'depth': 365,
 'say': 366,
 'eye': 367,
 'heroine': 368,
 'city': 369,
 'terrible': 370,
 'daughter': 371,
 'monster': 372,
 'home': 373,
 'expect': 374,
 'try': 375,
 'trying': 376,
 'three': 377,
 'kind': 378,
 'once': 379,
 'doing': 380,
 'fact': 381,
 'tv': 382,
 'perfect': 383,
 'lines': 384,
 'comes': 385,
 'tone': 386,
 'tony': 387,
 'easy': 388,
 'cusack': 389,
 'holes': 390,
 'detective': 391,
 'powerful': 392,
 'politics': 393,
 'odd': 394,
 'thru': 395,
 'former': 396,
 'key': 397,
 'open': 398,
 'few': 399,
 'family': 400,
 'day': 401,
 'fair': 402,
 'experience': 403,
 'events': 404,
 'fantastic': 405,
 'turns': 406,
 'alien': 407,
 'dialogue': 408,
 'sets': 409,
 'hollywood': 410,
 'stock': 411,
 'supposed': 412,
 'might': 413,
 'forward': 414,
 'dumb': 415,
 'blonde': 416,
 'maybe': 417,
 'version': 418,
 'scary': 419,
 'roles': 420,
 'older': 421,
 'lee': 422,
 'cheap': 423,
 'standard': 424,
 'top': 425,
 'called': 426,
 'uses': 427,
 'future': 428,
 'heads': 429,
 'reality': 430,
 'power': 431,
 'child': 432,
 'together': 433,
 'sequence': 434,
 'truly': 435,
 'villains': 436,
 'come': 437,
 'next': 438,
 'understand': 439,
 'least': 440,
 'unbelievable': 441,
 'name': 442,
 'value': 443,
 'carrigan': 444,
 'reason': 445,
 'dramatic': 446,
 'attention': 447,
 'major': 448,
 'ridiculous': 449,
 'issues': 450,
 'air': 451,
 'against': 452,
 'already': 453,
 'course': 454,
 'looked': 455,
 'low': 456,
 'attempt': 457,
 'd': 458,
 'lost': 459,
 'danny': 460,
 'anti': 461,
 'charge': 462,
 'picture': 463,
 'appearing': 464,
 'deserves': 465,
 'aren': 466,
 'everyone': 467,
 'son': 468,
 'spectacular': 469,
 'fashion': 470,
 'andie': 471,
 'predictable': 472,
 'yes': 473,
 'costumes': 474,
 'forced': 475,
 'development': 476,
 'beautifully': 477,
 'convincing': 478,
 'lack': 479,
 'mother': 480,
 'age': 481,
 'run': 482,
 'fight': 483,
 'move': 484,
 'talent': 485,
 'william': 486,
 'leaving': 487,
 'happen': 488,
 'saw': 489,
 'wasted': 490,
 'themselves': 491,
 'ways': 492,
 'gay': 493,
 'worse': 494,
 'dreams': 495,
 'wife': 496,
 'sure': 497,
 'group': 498,
 'sounds': 499,
 'hit': 500,
 'head': 501,
 'classic': 502,
 'dimensional': 503,
 'michael': 504,
 'gives': 505,
 'believable': 506,
 'muslim': 507,
 'farik': 508,
 'julia': 509,
 'begins': 510,
 'female': 511,
 'male': 512,
 'must': 513,
 'charlie': 514,
 'bobby': 515,
 'earl': 516,
 'further': 517,
 'killer': 518,
 'mystery': 519,
 'creature': 520,
 'feels': 521,
 'entertaining': 522,
 'certainly': 523,
 'somewhat': 524,
 'portray': 525,
 'nature': 526,
 'boy': 527,
 'keep': 528,
 'hoped': 529,
 'before': 530,
 'disjointed': 531,
 'form': 532,
 'comic': 533,
 'death': 534,
 'gamera': 535,
 'father': 536,
 'kids': 537,
 'follow': 538,
 'romantic': 539,
 'leads': 540,
 'twist': 541,
 'fame': 542,
 'u': 543,
 'your': 544,
 'tension': 545,
 'used': 546,
 'human': 547,
 'thomas': 548,
 'based': 549,
 'stuff': 550,
 'jean': 551,
 'b': 552,
 'start': 553,
 'slowly': 554,
 'sort': 555,
 'hell': 556,
 'special': 557,
 'dressed': 558,
 'sister': 559,
 'goes': 560,
 'decent': 561,
 'horses': 562,
 'along': 563,
 'queen': 564,
 'high': 565,
 'school': 566,
 'mcqueen': 567,
 'play': 568,
 'tries': 569,
 'hall': 570,
 'natural': 571,
 'may': 572,
 'attractive': 573,
 'living': 574,
 'absolutely': 575,
 'frank': 576,
 'likable': 577,
 'brilliant': 578,
 'jason': 579,
 'coming': 580,
 'america': 581,
 'v': 582,
 'college': 583,
 'mountains': 584,
 'presence': 585,
 'poorly': 586,
 'point': 587,
 'else': 588,
 'realistic': 589,
 'japanese': 590,
 'location': 591,
 'basic': 592,
 'lesson': 593,
 'morality': 594,
 'luck': 595,
 'backdrop': 596,
 'smooth': 597,
 'surreal': 598,
 '4': 599,
 'c': 600,
 'evocative': 601,
 'visually': 602,
 'overall': 603,
 'grows': 604,
 'maturity': 605,
 'explored': 606,
 'enjoyed': 607,
 'red': 608,
 'puts': 609,
 'stylish': 610,
 'documentary': 611,
 'places': 612,
 'beatrice': 613,
 'giving': 614,
 'benedict': 615,
 'ups': 616,
 'include': 617,
 'episode': 618,
 'entertainment': 619,
 'humour': 620,
 'sheer': 621,
 'meets': 622,
 'boys': 623,
 'ray': 624,
 'build': 625,
 'managed': 626,
 '1950s': 627,
 'dead': 628,
 'stereotypes': 629,
 'less': 630,
 'mediocre': 631,
 'known': 632,
 'example': 633,
 'happens': 634,
 'filmmakers': 635,
 'added': 636,
 'persona': 637,
 'allows': 638,
 'range': 639,
 'heavy': 640,
 'fault': 641,
 'effort': 642,
 'word': 643,
 'pierce': 644,
 'patrick': 645,
 'mid': 646,
 '90s': 647,
 'quirky': 648,
 'mood': 649,
 'tell': 650,
 'plain': 651,
 'climax': 652,
 'mask': 653,
 'sketchy': 654,
 'post': 655,
 'hunting': 656,
 'humans': 657,
 'nowhere': 658,
 'near': 659,
 'rape': 660,
 'points': 661,
 'throughout': 662,
 'mind': 663,
 'murder': 664,
 'driver': 665,
 'completely': 666,
 'either': 667,
 'wears': 668,
 'waste': 669,
 'thinks': 670,
 'zane': 671,
 '2': 672,
 'casting': 673,
 'directors': 674,
 'care': 675,
 'dies': 676,
 'compared': 677,
 'de': 678,
 'depths': 679,
 'publicity': 680,
 'bush': 681,
 'score': 682,
 'lucky': 683,
 'graphics': 684,
 'resolution': 685,
 'pair': 686,
 'touching': 687,
 'lies': 688,
 'heart': 689,
 'likely': 690,
 'typical': 691,
 'won': 692,
 'oscar': 693,
 'nicholas': 694,
 'complex': 695,
 'contrasted': 696,
 'moral': 697,
 'society': 698,
 'retreat': 699,
 'corrupt': 700,
 'french': 701,
 'simple': 702,
 'case': 703,
 'vivid': 704,
 'ethereal': 705,
 'atmosphere': 706,
 'forest': 707,
 'branch': 708,
 'mysterious': 709,
 'americans': 710,
 'racing': 711,
 'away': 712,
 'suppose': 713,
 'expected': 714,
 'words': 715,
 'interested': 716,
 'happening': 717,
 'help': 718,
 'couldn': 719,
 'exists': 720,
 'trust': 721,
 'message': 722,
 'police': 723,
 'appears': 724,
 'failure': 725,
 'journey': 726,
 'amount': 727,
 'cinematographer': 728,
 'names': 729,
 'aunt': 730,
 'lady': 731,
 'jacqueline': 732,
 'room': 733,
 'apparently': 734,
 'captured': 735,
 'lens': 736,
 'impression': 737,
 'bothered': 738,
 'faces': 739,
 'background': 740,
 'sad': 741,
 'die': 742,
 'content': 743,
 'nail': 744,
 'lovely': 745,
 'jeff': 746,
 'anthony': 747,
 'chinese': 748,
 'restored': 749,
 'shouting': 750,
 'itself': 751,
 'thoroughly': 752,
 'thoughtful': 753,
 'george': 754,
 'countryside': 755,
 'year': 756,
 'mean': 757,
 'neither': 758,
 'ones': 759,
 'leslie': 760,
 'jr': 761,
 'direction': 762,
 'dreadful': 763,
 'workers': 764,
 'china': 765,
 'owner': 766,
 'amazingly': 767,
 'filled': 768,
 'writing': 769,
 'agent': 770,
 'eastern': 771,
 'simply': 772,
 'someone': 773,
 'scholar': 774,
 'emotional': 775,
 'struggle': 776,
 'torn': 777,
 'god': 778,
 'bardem': 779,
 'bed': 780,
 'scorpion': 781,
 'car': 782,
 'breathtaker': 783,
 'lingering': 784,
 'took': 785,
 'cold': 786,
 'angels': 787,
 '1979': 788,
 '1980': 789,
 'armstrong': 790,
 'victim': 791,
 'blair': 792,
 'upon': 793,
 'gorgeous': 794,
 'box': 795,
 'cool': 796,
 'cover': 797,
 '50': 798,
 'everyday': 799,
 'deep': 800,
 'allow': 801,
 'afraid': 802,
 'candy': 803,
 'imaginative': 804,
 'portrays': 805,
 'bought': 806,
 'water': 807,
 'am': 808,
 'items': 809,
 'creative': 810,
 'process': 811,
 'forces': 812,
 'plastic': 813,
 'trees': 814,
 'basically': 815,
 'worth': 816,
 'follows': 817,
 'cope': 818,
 'losing': 819,
 'killed': 820,
 '70': 821,
 'hysteria': 822,
 'musical': 823,
 'sex': 824,
 'gary': 825,
 'quest': 826,
 'win': 827,
 'road': 828,
 'surprise': 829,
 'pictured': 830,
 'mere': 831,
 'yourself': 832,
 'fancy': 833,
 'howard': 834,
 'vulnerable': 835,
 'king': 836,
 'impact': 837,
 'mason': 838,
 'guide': 839,
 'usual': 840,
 'slick': 841,
 'matt': 842,
 'duke': 843,
 'anyone': 844,
 'wanted': 845,
 'stereotypical': 846,
 'silly': 847,
 'wish': 848,
 'dev': 849,
 'jasbir': 850,
 'parker': 851,
 'frequently': 852,
 'annoying': 853,
 'showing': 854,
 'minutes': 855,
 'talks': 856,
 'view': 857,
 'piece': 858,
 'transformation': 859,
 'll': 860,
 'single': 861,
 'let': 862,
 'pay': 863,
 'steve': 864,
 'bring': 865,
 'proceedings': 866,
 'campaign': 867,
 'dim': 868,
 'cillian': 869,
 'murphy': 870,
 'highly': 871,
 'professional': 872,
 'effect': 873,
 'pass': 874,
 'minimal': 875,
 'rose': 876,
 '80': 877,
 'brian': 878,
 'band': 879,
 'stands': 880,
 'strange': 881,
 'due': 882,
 'artistic': 883,
 'unknown': 884,
 'situation': 885,
 'clever': 886,
 'dad': 887,
 'talk': 888,
 'surprised': 889,
 'root': 890,
 'self': 891,
 'somehow': 892,
 'intentionally': 893,
 'file': 894,
 'intelligence': 895,
 'talented': 896,
 'delivered': 897,
 'unique': 898,
 'charm': 899,
 'behind': 900,
 'manages': 901,
 'inside': 902,
 'stepson': 903,
 'humiliating': 904,
 'appear': 905,
 '3': 906,
 'bill': 907,
 'stuck': 908,
 'luis': 909,
 'blurred': 910,
 'blood': 911,
 '90': 912,
 'melodrama': 913,
 'twists': 914,
 'decision': 915,
 'needs': 916,
 'person': 917,
 'drake': 918,
 'bell': 919,
 'put': 920,
 'christopher': 921,
 'mcdonald': 922,
 'supporting': 923,
 'meant': 924,
 'bourne': 925,
 'fully': 926,
 'become': 927,
 'attached': 928,
 'obviously': 929,
 'clear': 930,
 'felix': 931,
 'whose': 932,
 'business': 933,
 'image': 934,
 'ship': 935,
 'colored': 936,
 'screenplay': 937,
 'finds': 938,
 'design': 939,
 'class': 940,
 'fairly': 941,
 'mini': 942,
 'during': 943,
 'antoni': 944,
 'meet': 945,
 'creepy': 946,
 'incredibly': 947,
 'goofy': 948,
 'humor': 949,
 'downey': 950,
 'mr': 951,
 'chance': 952,
 'acted': 953,
 'edge': 954,
 'incredible': 955,
 'outstanding': 956,
 'friend': 957,
 'paternal': 958,
 'towards': 959,
 'rock': 960,
 'revenge': 961,
 'sly': 962,
 'flashback': 963,
 'mostly': 964,
 'now': 965,
 'adele': 966,
 'ann': 967,
 'sarandon': 968,
 'portman': 969,
 'actress': 970,
 'walt': 971,
 'interactions': 972,
 'patients': 973,
 'cell': 974,
 'pick': 975,
 'political': 976,
 'aspect': 977,
 'gus': 978,
 'weird': 979,
 'area': 980,
 'uber': 981,
 'coldness': 982,
 'brought': 983,
 'aboard': 984,
 'falling': 985,
 'bullets': 986,
 'pull': 987,
 'travel': 988,
 'storyline': 989,
 'parents': 990,
 'mercedes': 991,
 'tromeo': 992,
 'consisting': 993,
 'framing': 994,
 'mrs': 995,
 'later': 996,
 'sees': 997,
 'natasha': 998,
 'gregson': 999,
 'wagner': 1000,
 'potential': 1001}

In [79]:
vocab["<unk>"] = 0
vocab["<pad>"] = 1

In [80]:
vocab

{'the': 2,
 'a': 3,
 'and': 4,
 'of': 5,
 'is': 6,
 'to': 7,
 'in': 8,
 'it': 9,
 's': 10,
 'that': 11,
 'this': 12,
 'as': 13,
 'i': 14,
 'was': 15,
 'film': 16,
 'for': 17,
 'with': 18,
 'movie': 19,
 'are': 20,
 'his': 21,
 'on': 22,
 'not': 23,
 'they': 24,
 'story': 25,
 'very': 26,
 't': 27,
 'be': 28,
 'he': 29,
 'but': 30,
 'one': 31,
 'all': 32,
 'an': 33,
 'at': 34,
 'some': 35,
 'have': 36,
 'good': 37,
 'characters': 38,
 'you': 39,
 'by': 40,
 'has': 41,
 'like': 42,
 'about': 43,
 'out': 44,
 'or': 45,
 'just': 46,
 'who': 47,
 'there': 48,
 'only': 49,
 'their': 50,
 'her': 51,
 'great': 52,
 'character': 53,
 'more': 54,
 'really': 55,
 'camera': 56,
 'so': 57,
 'also': 58,
 'what': 59,
 'were': 60,
 'can': 61,
 'plot': 62,
 'up': 63,
 'do': 64,
 'into': 65,
 'much': 66,
 'even': 67,
 'work': 68,
 'most': 69,
 'been': 70,
 'best': 71,
 'would': 72,
 'bad': 73,
 'man': 74,
 'from': 75,
 'look': 76,
 'scenes': 77,
 'than': 78,
 'time': 79,
 'acting': 80,
 'its': 81,
 'she': 82,
 'two': 83,
 'way': 84,
 'we': 85,
 'people': 86,
 'other': 87,
 'how': 88,
 'which': 89,
 'too': 90,
 'cinematography': 91,
 'black': 92,
 'could': 93,
 'many': 94,
 'actors': 95,
 'shot': 96,
 'love': 97,
 'interesting': 98,
 'well': 99,
 'him': 100,
 'performance': 101,
 'ever': 102,
 'see': 103,
 'no': 104,
 'made': 105,
 'had': 106,
 'excellent': 107,
 'young': 108,
 'over': 109,
 'first': 110,
 'make': 111,
 'being': 112,
 'any': 113,
 'looks': 114,
 'shots': 115,
 'me': 116,
 'will': 117,
 'when': 118,
 'little': 119,
 'my': 120,
 'guy': 121,
 'girl': 122,
 'here': 123,
 'better': 124,
 'does': 125,
 'find': 126,
 'doesn': 127,
 'seems': 128,
 'effects': 129,
 'off': 130,
 'life': 131,
 'ending': 132,
 'if': 133,
 'white': 134,
 'cast': 135,
 'get': 136,
 'nice': 137,
 'different': 138,
 'world': 139,
 'don': 140,
 'role': 141,
 'rather': 142,
 'lot': 143,
 'beautiful': 144,
 'while': 145,
 'movies': 146,
 'end': 147,
 'feel': 148,
 'job': 149,
 'always': 150,
 'show': 151,
 'between': 152,
 'did': 153,
 'through': 154,
 'where': 155,
 'watch': 156,
 'gets': 157,
 'takes': 158,
 'woman': 159,
 'same': 160,
 'wonderful': 161,
 'short': 162,
 'filmed': 163,
 'know': 164,
 'watching': 165,
 'played': 166,
 'sense': 167,
 'use': 168,
 'scene': 169,
 'them': 170,
 'didn': 171,
 'photography': 172,
 'enough': 173,
 'fun': 174,
 'because': 175,
 'think': 176,
 'long': 177,
 'big': 178,
 'go': 179,
 'real': 180,
 'full': 181,
 'then': 182,
 'script': 183,
 'set': 184,
 'almost': 185,
 'actor': 186,
 'superb': 187,
 'each': 188,
 'drama': 189,
 'around': 190,
 'anything': 191,
 'after': 192,
 'everything': 193,
 'yet': 194,
 'still': 195,
 'plays': 196,
 'past': 197,
 'voice': 198,
 'never': 199,
 'something': 200,
 'women': 201,
 'lighting': 202,
 'especially': 203,
 'why': 204,
 'loved': 205,
 'act': 206,
 'both': 207,
 'town': 208,
 'pretty': 209,
 'lead': 210,
 'idea': 211,
 'us': 212,
 'makes': 213,
 'quite': 214,
 'perfectly': 215,
 'done': 216,
 'awful': 217,
 'series': 218,
 'comedy': 219,
 'poor': 220,
 'fine': 221,
 'john': 222,
 'actually': 223,
 'thought': 224,
 'believe': 225,
 'getting': 226,
 'far': 227,
 'looking': 228,
 'action': 229,
 'lives': 230,
 'audience': 231,
 'true': 232,
 'whole': 233,
 'focus': 234,
 'himself': 235,
 'children': 236,
 'horrible': 237,
 'hard': 238,
 'music': 239,
 'seen': 240,
 'non': 241,
 'funny': 242,
 'performances': 243,
 'richard': 244,
 'quality': 245,
 'new': 246,
 'old': 247,
 'screen': 248,
 'instead': 249,
 'visuals': 250,
 'cave': 251,
 'filming': 252,
 'men': 253,
 'right': 254,
 'thing': 255,
 'robert': 256,
 'color': 257,
 'part': 258,
 'ben': 259,
 'times': 260,
 'years': 261,
 'nothing': 262,
 'jack': 263,
 'original': 264,
 'seemed': 265,
 'boring': 266,
 'kid': 267,
 'impressive': 268,
 'early': 269,
 'dark': 270,
 'own': 271,
 're': 272,
 'hero': 273,
 'entire': 274,
 'shows': 275,
 'dream': 276,
 'got': 277,
 've': 278,
 'm': 279,
 'opening': 280,
 'important': 281,
 'such': 282,
 'face': 283,
 'small': 284,
 'editing': 285,
 'feeling': 286,
 'stunning': 287,
 'style': 288,
 'guys': 289,
 'left': 290,
 'portrayal': 291,
 'wants': 292,
 'angles': 293,
 'works': 294,
 'video': 295,
 'isn': 296,
 'parts': 297,
 'images': 298,
 'bit': 299,
 'half': 300,
 'back': 301,
 'main': 302,
 'making': 303,
 'nearly': 304,
 'another': 305,
 'american': 306,
 'playing': 307,
 'change': 308,
 'couple': 309,
 'middle': 310,
 'relationship': 311,
 'animation': 312,
 'imagery': 313,
 'footage': 314,
 'however': 315,
 'fans': 316,
 'viewer': 317,
 'without': 318,
 'x': 319,
 'seem': 320,
 'constant': 321,
 'stories': 322,
 'given': 323,
 'budget': 324,
 'take': 325,
 'four': 326,
 'effective': 327,
 'create': 328,
 'found': 329,
 'amazing': 330,
 'killing': 331,
 'down': 332,
 'star': 333,
 'clearly': 334,
 'those': 335,
 'emotions': 336,
 'evil': 337,
 'going': 338,
 'war': 339,
 'give': 340,
 'again': 341,
 'although': 342,
 'though': 343,
 'having': 344,
 'murky': 345,
 'scenery': 346,
 'country': 347,
 'visual': 348,
 'book': 349,
 'edie': 350,
 'close': 351,
 'under': 352,
 'turn': 353,
 'things': 354,
 'strong': 355,
 'psychological': 356,
 'horror': 357,
 'certain': 358,
 'entirely': 359,
 'worst': 360,
 'every': 361,
 'these': 362,
 'straight': 363,
 'line': 364,
 'depth': 365,
 'say': 366,
 'eye': 367,
 'heroine': 368,
 'city': 369,
 'terrible': 370,
 'daughter': 371,
 'monster': 372,
 'home': 373,
 'expect': 374,
 'try': 375,
 'trying': 376,
 'three': 377,
 'kind': 378,
 'once': 379,
 'doing': 380,
 'fact': 381,
 'tv': 382,
 'perfect': 383,
 'lines': 384,
 'comes': 385,
 'tone': 386,
 'tony': 387,
 'easy': 388,
 'cusack': 389,
 'holes': 390,
 'detective': 391,
 'powerful': 392,
 'politics': 393,
 'odd': 394,
 'thru': 395,
 'former': 396,
 'key': 397,
 'open': 398,
 'few': 399,
 'family': 400,
 'day': 401,
 'fair': 402,
 'experience': 403,
 'events': 404,
 'fantastic': 405,
 'turns': 406,
 'alien': 407,
 'dialogue': 408,
 'sets': 409,
 'hollywood': 410,
 'stock': 411,
 'supposed': 412,
 'might': 413,
 'forward': 414,
 'dumb': 415,
 'blonde': 416,
 'maybe': 417,
 'version': 418,
 'scary': 419,
 'roles': 420,
 'older': 421,
 'lee': 422,
 'cheap': 423,
 'standard': 424,
 'top': 425,
 'called': 426,
 'uses': 427,
 'future': 428,
 'heads': 429,
 'reality': 430,
 'power': 431,
 'child': 432,
 'together': 433,
 'sequence': 434,
 'truly': 435,
 'villains': 436,
 'come': 437,
 'next': 438,
 'understand': 439,
 'least': 440,
 'unbelievable': 441,
 'name': 442,
 'value': 443,
 'carrigan': 444,
 'reason': 445,
 'dramatic': 446,
 'attention': 447,
 'major': 448,
 'ridiculous': 449,
 'issues': 450,
 'air': 451,
 'against': 452,
 'already': 453,
 'course': 454,
 'looked': 455,
 'low': 456,
 'attempt': 457,
 'd': 458,
 'lost': 459,
 'danny': 460,
 'anti': 461,
 'charge': 462,
 'picture': 463,
 'appearing': 464,
 'deserves': 465,
 'aren': 466,
 'everyone': 467,
 'son': 468,
 'spectacular': 469,
 'fashion': 470,
 'andie': 471,
 'predictable': 472,
 'yes': 473,
 'costumes': 474,
 'forced': 475,
 'development': 476,
 'beautifully': 477,
 'convincing': 478,
 'lack': 479,
 'mother': 480,
 'age': 481,
 'run': 482,
 'fight': 483,
 'move': 484,
 'talent': 485,
 'william': 486,
 'leaving': 487,
 'happen': 488,
 'saw': 489,
 'wasted': 490,
 'themselves': 491,
 'ways': 492,
 'gay': 493,
 'worse': 494,
 'dreams': 495,
 'wife': 496,
 'sure': 497,
 'group': 498,
 'sounds': 499,
 'hit': 500,
 'head': 501,
 'classic': 502,
 'dimensional': 503,
 'michael': 504,
 'gives': 505,
 'believable': 506,
 'muslim': 507,
 'farik': 508,
 'julia': 509,
 'begins': 510,
 'female': 511,
 'male': 512,
 'must': 513,
 'charlie': 514,
 'bobby': 515,
 'earl': 516,
 'further': 517,
 'killer': 518,
 'mystery': 519,
 'creature': 520,
 'feels': 521,
 'entertaining': 522,
 'certainly': 523,
 'somewhat': 524,
 'portray': 525,
 'nature': 526,
 'boy': 527,
 'keep': 528,
 'hoped': 529,
 'before': 530,
 'disjointed': 531,
 'form': 532,
 'comic': 533,
 'death': 534,
 'gamera': 535,
 'father': 536,
 'kids': 537,
 'follow': 538,
 'romantic': 539,
 'leads': 540,
 'twist': 541,
 'fame': 542,
 'u': 543,
 'your': 544,
 'tension': 545,
 'used': 546,
 'human': 547,
 'thomas': 548,
 'based': 549,
 'stuff': 550,
 'jean': 551,
 'b': 552,
 'start': 553,
 'slowly': 554,
 'sort': 555,
 'hell': 556,
 'special': 557,
 'dressed': 558,
 'sister': 559,
 'goes': 560,
 'decent': 561,
 'horses': 562,
 'along': 563,
 'queen': 564,
 'high': 565,
 'school': 566,
 'mcqueen': 567,
 'play': 568,
 'tries': 569,
 'hall': 570,
 'natural': 571,
 'may': 572,
 'attractive': 573,
 'living': 574,
 'absolutely': 575,
 'frank': 576,
 'likable': 577,
 'brilliant': 578,
 'jason': 579,
 'coming': 580,
 'america': 581,
 'v': 582,
 'college': 583,
 'mountains': 584,
 'presence': 585,
 'poorly': 586,
 'point': 587,
 'else': 588,
 'realistic': 589,
 'japanese': 590,
 'location': 591,
 'basic': 592,
 'lesson': 593,
 'morality': 594,
 'luck': 595,
 'backdrop': 596,
 'smooth': 597,
 'surreal': 598,
 '4': 599,
 'c': 600,
 'evocative': 601,
 'visually': 602,
 'overall': 603,
 'grows': 604,
 'maturity': 605,
 'explored': 606,
 'enjoyed': 607,
 'red': 608,
 'puts': 609,
 'stylish': 610,
 'documentary': 611,
 'places': 612,
 'beatrice': 613,
 'giving': 614,
 'benedict': 615,
 'ups': 616,
 'include': 617,
 'episode': 618,
 'entertainment': 619,
 'humour': 620,
 'sheer': 621,
 'meets': 622,
 'boys': 623,
 'ray': 624,
 'build': 625,
 'managed': 626,
 '1950s': 627,
 'dead': 628,
 'stereotypes': 629,
 'less': 630,
 'mediocre': 631,
 'known': 632,
 'example': 633,
 'happens': 634,
 'filmmakers': 635,
 'added': 636,
 'persona': 637,
 'allows': 638,
 'range': 639,
 'heavy': 640,
 'fault': 641,
 'effort': 642,
 'word': 643,
 'pierce': 644,
 'patrick': 645,
 'mid': 646,
 '90s': 647,
 'quirky': 648,
 'mood': 649,
 'tell': 650,
 'plain': 651,
 'climax': 652,
 'mask': 653,
 'sketchy': 654,
 'post': 655,
 'hunting': 656,
 'humans': 657,
 'nowhere': 658,
 'near': 659,
 'rape': 660,
 'points': 661,
 'throughout': 662,
 'mind': 663,
 'murder': 664,
 'driver': 665,
 'completely': 666,
 'either': 667,
 'wears': 668,
 'waste': 669,
 'thinks': 670,
 'zane': 671,
 '2': 672,
 'casting': 673,
 'directors': 674,
 'care': 675,
 'dies': 676,
 'compared': 677,
 'de': 678,
 'depths': 679,
 'publicity': 680,
 'bush': 681,
 'score': 682,
 'lucky': 683,
 'graphics': 684,
 'resolution': 685,
 'pair': 686,
 'touching': 687,
 'lies': 688,
 'heart': 689,
 'likely': 690,
 'typical': 691,
 'won': 692,
 'oscar': 693,
 'nicholas': 694,
 'complex': 695,
 'contrasted': 696,
 'moral': 697,
 'society': 698,
 'retreat': 699,
 'corrupt': 700,
 'french': 701,
 'simple': 702,
 'case': 703,
 'vivid': 704,
 'ethereal': 705,
 'atmosphere': 706,
 'forest': 707,
 'branch': 708,
 'mysterious': 709,
 'americans': 710,
 'racing': 711,
 'away': 712,
 'suppose': 713,
 'expected': 714,
 'words': 715,
 'interested': 716,
 'happening': 717,
 'help': 718,
 'couldn': 719,
 'exists': 720,
 'trust': 721,
 'message': 722,
 'police': 723,
 'appears': 724,
 'failure': 725,
 'journey': 726,
 'amount': 727,
 'cinematographer': 728,
 'names': 729,
 'aunt': 730,
 'lady': 731,
 'jacqueline': 732,
 'room': 733,
 'apparently': 734,
 'captured': 735,
 'lens': 736,
 'impression': 737,
 'bothered': 738,
 'faces': 739,
 'background': 740,
 'sad': 741,
 'die': 742,
 'content': 743,
 'nail': 744,
 'lovely': 745,
 'jeff': 746,
 'anthony': 747,
 'chinese': 748,
 'restored': 749,
 'shouting': 750,
 'itself': 751,
 'thoroughly': 752,
 'thoughtful': 753,
 'george': 754,
 'countryside': 755,
 'year': 756,
 'mean': 757,
 'neither': 758,
 'ones': 759,
 'leslie': 760,
 'jr': 761,
 'direction': 762,
 'dreadful': 763,
 'workers': 764,
 'china': 765,
 'owner': 766,
 'amazingly': 767,
 'filled': 768,
 'writing': 769,
 'agent': 770,
 'eastern': 771,
 'simply': 772,
 'someone': 773,
 'scholar': 774,
 'emotional': 775,
 'struggle': 776,
 'torn': 777,
 'god': 778,
 'bardem': 779,
 'bed': 780,
 'scorpion': 781,
 'car': 782,
 'breathtaker': 783,
 'lingering': 784,
 'took': 785,
 'cold': 786,
 'angels': 787,
 '1979': 788,
 '1980': 789,
 'armstrong': 790,
 'victim': 791,
 'blair': 792,
 'upon': 793,
 'gorgeous': 794,
 'box': 795,
 'cool': 796,
 'cover': 797,
 '50': 798,
 'everyday': 799,
 'deep': 800,
 'allow': 801,
 'afraid': 802,
 'candy': 803,
 'imaginative': 804,
 'portrays': 805,
 'bought': 806,
 'water': 807,
 'am': 808,
 'items': 809,
 'creative': 810,
 'process': 811,
 'forces': 812,
 'plastic': 813,
 'trees': 814,
 'basically': 815,
 'worth': 816,
 'follows': 817,
 'cope': 818,
 'losing': 819,
 'killed': 820,
 '70': 821,
 'hysteria': 822,
 'musical': 823,
 'sex': 824,
 'gary': 825,
 'quest': 826,
 'win': 827,
 'road': 828,
 'surprise': 829,
 'pictured': 830,
 'mere': 831,
 'yourself': 832,
 'fancy': 833,
 'howard': 834,
 'vulnerable': 835,
 'king': 836,
 'impact': 837,
 'mason': 838,
 'guide': 839,
 'usual': 840,
 'slick': 841,
 'matt': 842,
 'duke': 843,
 'anyone': 844,
 'wanted': 845,
 'stereotypical': 846,
 'silly': 847,
 'wish': 848,
 'dev': 849,
 'jasbir': 850,
 'parker': 851,
 'frequently': 852,
 'annoying': 853,
 'showing': 854,
 'minutes': 855,
 'talks': 856,
 'view': 857,
 'piece': 858,
 'transformation': 859,
 'll': 860,
 'single': 861,
 'let': 862,
 'pay': 863,
 'steve': 864,
 'bring': 865,
 'proceedings': 866,
 'campaign': 867,
 'dim': 868,
 'cillian': 869,
 'murphy': 870,
 'highly': 871,
 'professional': 872,
 'effect': 873,
 'pass': 874,
 'minimal': 875,
 'rose': 876,
 '80': 877,
 'brian': 878,
 'band': 879,
 'stands': 880,
 'strange': 881,
 'due': 882,
 'artistic': 883,
 'unknown': 884,
 'situation': 885,
 'clever': 886,
 'dad': 887,
 'talk': 888,
 'surprised': 889,
 'root': 890,
 'self': 891,
 'somehow': 892,
 'intentionally': 893,
 'file': 894,
 'intelligence': 895,
 'talented': 896,
 'delivered': 897,
 'unique': 898,
 'charm': 899,
 'behind': 900,
 'manages': 901,
 'inside': 902,
 'stepson': 903,
 'humiliating': 904,
 'appear': 905,
 '3': 906,
 'bill': 907,
 'stuck': 908,
 'luis': 909,
 'blurred': 910,
 'blood': 911,
 '90': 912,
 'melodrama': 913,
 'twists': 914,
 'decision': 915,
 'needs': 916,
 'person': 917,
 'drake': 918,
 'bell': 919,
 'put': 920,
 'christopher': 921,
 'mcdonald': 922,
 'supporting': 923,
 'meant': 924,
 'bourne': 925,
 'fully': 926,
 'become': 927,
 'attached': 928,
 'obviously': 929,
 'clear': 930,
 'felix': 931,
 'whose': 932,
 'business': 933,
 'image': 934,
 'ship': 935,
 'colored': 936,
 'screenplay': 937,
 'finds': 938,
 'design': 939,
 'class': 940,
 'fairly': 941,
 'mini': 942,
 'during': 943,
 'antoni': 944,
 'meet': 945,
 'creepy': 946,
 'incredibly': 947,
 'goofy': 948,
 'humor': 949,
 'downey': 950,
 'mr': 951,
 'chance': 952,
 'acted': 953,
 'edge': 954,
 'incredible': 955,
 'outstanding': 956,
 'friend': 957,
 'paternal': 958,
 'towards': 959,
 'rock': 960,
 'revenge': 961,
 'sly': 962,
 'flashback': 963,
 'mostly': 964,
 'now': 965,
 'adele': 966,
 'ann': 967,
 'sarandon': 968,
 'portman': 969,
 'actress': 970,
 'walt': 971,
 'interactions': 972,
 'patients': 973,
 'cell': 974,
 'pick': 975,
 'political': 976,
 'aspect': 977,
 'gus': 978,
 'weird': 979,
 'area': 980,
 'uber': 981,
 'coldness': 982,
 'brought': 983,
 'aboard': 984,
 'falling': 985,
 'bullets': 986,
 'pull': 987,
 'travel': 988,
 'storyline': 989,
 'parents': 990,
 'mercedes': 991,
 'tromeo': 992,
 'consisting': 993,
 'framing': 994,
 'mrs': 995,
 'later': 996,
 'sees': 997,
 'natasha': 998,
 'gregson': 999,
 'wagner': 1000,
 'potential': 1001,
 ...}

### Task 10

Using the vocabulary, create a function named `encode_text` that tokenizes and encodes each review text into a sequence of token IDs.
- specify the inputs `text` and `vocab`
    - `text` will be the raw review text to be tokenized and encoded
    - `vocab` is the vocabulary
- apply the `tokenize` function to the input `text`
- encode the tokenized text into a sequence of token IDs
    - assign the token ID value for the special token `<unk>` for word tokens that are not in the vocabulary
- the function should return the encoded review text

In [81]:
def encode_text(text, vocab):
    tokenized_text = tokenize_review(text)
    encoded_text = [vocab.get(word, vocab['<unk>']) for word in tokenized_text]
    return encoded_text

### Task 11

Let's create another function named `pad_or_truncate` that pre-processes each encoded text to have the same length specified by a maximum length value.
- specify the inputs `encoded_text` and `max_len`
    - `encoded_text` will be the input encoded review text
    - `max_len` is the specified maximum length value
- use an `if` statement to identify reviews longer than the maximum length and returns the review truncated to the maximum length value
- use an `else` statement to identify reviews shorter than the maximum length and returns the review padded with `1` values (corresponding to the token ID for the special token `<pad>`)

In [82]:
def pad_or_truncate(encoded_text, max_len):
    if len(encoded_text) > max_len:
        return encoded_text[:max_len]
    else:
        return encoded_text + [1] * (max_len - len(encoded_text))

### Task 12

Now, let's fully tokenize and encode each review text by applying the `encode_text` and `pad_or_truncate` functions:
- specify a maximum length of `128` for each review text sequence and save the value to the variable `MAX_SEQ_LENGTH`
- tokenize and encode each review text as follows:
    - use a `for` loop to iterate through each training review text in `train_texts`
    - apply the `encode_text` function to each review text (be sure to specify the vocabulary)
    - apply the `pad_or_truncate` function to each encoded text (be sure to specify the maximum length value)
- save the fully pre-processed review text sequences to the variable `padded_text_seqs`

In [83]:
MAX_SEQ_LENGTH = 128
padded_text_seqs = [pad_or_truncate(encode_text(text, vocab), MAX_SEQ_LENGTH) for text in train_texts]

In [132]:
# padded_text_seqs[:10]

In [133]:
len(padded_text_seqs)

369

### Task 13

Let's prepare our text sequences to for training by converting them into PyTorch tensors:

- create the input tensor `X_tensor` by converting the padded/truncated sequences
- create the label tensor `y_tensor` by converting the training review labels (be sure to specify the datatype `torch.long`)

Using the PyTorch utility module `torch.utils.data`, let's organize the training input and label tensors into a single dataset object and an iterable that will allow us to load the training data in batches:
- create the variable `train_dataset` using the `TensorDataset` utility class to organize the input tensor and label tensor into a single dataset object
- create the variable `train_dataloader` using the `DataLoader` utility class to create an iterable that loads the `train_dataset` in batches of `16` (be sure to set `shuffle` to `True`)

In [134]:
X_tensor = torch.tensor(padded_text_seqs)
y_tensor = torch.tensor(train_labels, dtype=torch.long)

In [135]:
from torch.utils.data import TensorDataset, DataLoader
dataset = TensorDataset(X_tensor, y_tensor)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

## Task Group 3 - Training a Simple Neural Network

The first text classification model we'll build and train to classify movie reviews is a simple neural network with an embedding layer.

### Task 14

Let's construct the neural network architecture that will be trained to classify movie reviews!

Create a class named `SimpleNNWithEmbedding` for our neural network (using the PyTorch's `nn.Module`) with the following:

A. Create the `init` method that takes in the following attributes:
- `vocab_size` is the number of tokens in the vocabulary 
- `embed_size` is the embedding size
- `hidden_size` is the number of neurons in the linear layer
- `output_size` is the number of output classes

B. Build the `init` method by initializing the following layers:
- `self.embedding` is an embedding layer that creates embeddings equal to the vocabulary size with embedding sizes specified by the `embed_size` input
- `self.fc1` is the first linear layer with an input size equal to the embedding size in the embedding layer and an output size equal to the number of neurons in the hidden layer specified by the `hidden_size` input
- `self.fc2` is the second linear layer with an input size equal to the hidden size of the first linear layer and an output size equal to the number of classes specified by the `output_size` input

C. Build the `forward` method and create the forward operations in the following order:
1. Start by passing the input `x` into the embedding layer
2. Average the embeddings into a single representation
3. Pass the averaged embedding into the first linear layer
4. Apply the ReLU activation function 
5. Pass the activated output to the second linear layer
6. Return the output of the second linear layer

In [136]:
from torch import nn

class SimpleNNWithEmbedding(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size, output_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.fc1 = nn.Linear(embed_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.embedding(x)
        x = torch.mean(x, dim=1)
        x = self.fc1(x)
        x = torch.relu(x)
        x = self.fc2(x)
        return x

### Task 15

Next, let's create an instance of our `SimpleNNWithEmbedding` neural network class.

Start by defining the following variables:
- `vocab_size` - integer containing the vocabulary size (vocabulary length)
- `embed_size` - an embedding size of `50` dimensions for each token
- `hidden_size` - specifies the hidden layer in the neural network with `100` neurons
- `output_size` - specifies the number of class labels in our **multi-class** classification task
    - hint: each review will be classified as one of the following aspects: Cinematography, Characters, or Story
 
Instantiate the model with the variable parameters to the variable `text_classifier_nn`.

In [137]:
text_classifier_nn = SimpleNNWithEmbedding(vocab_size = len(vocab), embed_size=50, hidden_size=100, output_size=n_aspects)

### Task 16

Next, let's initialize the loss function and optimizer for training:
- create an instance of the **cross-entropy** loss function in PyTorch (from the `torch.nn` module) and save it to the variable `criterion`
- create an instance of the **Adam** optimizer in PyTorch (from the `torch.optim` module) with a learning rate of **0.005** and save it to the variable `optimizer

In [138]:
from torch import optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(text_classifier_nn.parameters(), lr=0.005)

### Task 17

Now let's train our neural network to classify movie reviews!

A. Create a function named `train_model` that takes in the following inputs:
- `model` is the text classification model
- `train_loader` is the training data contained in a PyTorch `DataLoader` object
- `criterion` is the loss function used to train the model
- `optimizer` is the optimizer used to train the model
- `num_epochs` is the number of training epochs

B. In the function, create a `for` loop that loops through the number of epochs specified by the input `num_epochs`. Within the loop:
- set the model to training mode
- track the loss per epoch by initializing the variable `epoch_loss` to `0.0`

C. Create a nested `for` loop within the first `for` loop such that:

1. Loops through the inputs and labels of each training batch in the input `train_loader` 
2. Reset the gradients at each iteration
3. Input the training batch through the forward pass
4. Calculate the cross-entropy loss
5. Backpropagate the loss through the network
6. Adjust the weights and biases
7. Update the total loss within the current training epoch

D. Run the function to train the `text_classifier_nn` model on the training dataset stored in the iterable `train_dataloader` using the loss-function saved in `criterion` and the optimizer saved in `optimizer` for `50` epochs.

In [139]:
def train_model(model, train_loader, criterion, optimizer, num_epochs):
    loss_history = []

    for epoch in range(num_epochs):
        model.train()
        epoch_loss = 0.0

        for batch_X, batch_y in train_loader:
            optimizer.zero_grad()

            output = model(batch_X)
            loss = criterion(output, batch_y)

            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg_epoch_loss = epoch_loss / len(train_loader)
        loss_history.append(avg_epoch_loss)

        print(f"Epoch {epoch+1}/{num_epochs}, Loss: {avg_epoch_loss:.4f}")

In [140]:
train_model(text_classifier_nn, dataloader, criterion, optimizer, 50)

Epoch 1/50, Loss: 1.1177
Epoch 2/50, Loss: 1.0809
Epoch 3/50, Loss: 1.0257
Epoch 4/50, Loss: 0.9804
Epoch 5/50, Loss: 0.9701
Epoch 6/50, Loss: 0.9475
Epoch 7/50, Loss: 0.9296
Epoch 8/50, Loss: 0.8700
Epoch 9/50, Loss: 0.8208
Epoch 10/50, Loss: 0.7399
Epoch 11/50, Loss: 0.6018
Epoch 12/50, Loss: 0.5241
Epoch 13/50, Loss: 0.4514
Epoch 14/50, Loss: 0.3436
Epoch 15/50, Loss: 0.3835
Epoch 16/50, Loss: 0.3291
Epoch 17/50, Loss: 0.3831
Epoch 18/50, Loss: 0.1734
Epoch 19/50, Loss: 0.1489
Epoch 20/50, Loss: 0.1162
Epoch 21/50, Loss: 0.0921
Epoch 22/50, Loss: 0.0883
Epoch 23/50, Loss: 0.0715
Epoch 24/50, Loss: 0.0616
Epoch 25/50, Loss: 0.0539
Epoch 26/50, Loss: 0.0444
Epoch 27/50, Loss: 0.0402
Epoch 28/50, Loss: 0.0392
Epoch 29/50, Loss: 0.0707
Epoch 30/50, Loss: 0.1359
Epoch 31/50, Loss: 0.0355
Epoch 32/50, Loss: 0.0241
Epoch 33/50, Loss: 0.0215
Epoch 34/50, Loss: 0.0179
Epoch 35/50, Loss: 0.0279
Epoch 36/50, Loss: 0.0167
Epoch 37/50, Loss: 0.0196
Epoch 38/50, Loss: 0.0190
Epoch 39/50, Loss: 0.0136
Epoch 40/50, Loss: 0.0116
Epoch 41/50, Loss: 0.0111
Epoch 42/50, Loss: 0.0120
Epoch 43/50, Loss: 0.0095
Epoch 44/50, Loss: 0.0099
Epoch 45/50, Loss: 0.0075
Epoch 46/50, Loss: 0.0096
Epoch 47/50, Loss: 0.0112
Epoch 48/50, Loss: 0.0073
Epoch 49/50, Loss: 0.0061
Epoch 50/50, Loss: 0.0066

### Task 18

Let's evaluate the trained neural network on an out-of-sample testing dataset.

Import the testing dataset stored in the CSV file `"datasets/imdb_movie_reviews_test.csv"` to a pandas DataFrame named `test_reviews_df`.

Then, create the _testing corpus_ by using the `.tolist()` function to convert the text sequence in each review and their corresponding aspect labels to the following lists:

- `test_texts` contains each movie review separated by commas
- `test_labels` contains each review aspect separated by commas

In [141]:
test_reviews_df = pd.read_csv("data/imdb_movie_reviews_test.csv", sep=",")
test_reviews_df.head()

,review,aspect,aspect_encoded
0,the cinematography is commonplace it at least ...,Cinematography,0
1,"The cinematography is OK', 'there are some pre...",Cinematography,0
2,the strangely annoying and unnecessary George ...,Characters,1
3,"Alyssa Milano', 'Tina Yothers', ""Edie McClurg ...",Characters,1
4,I loved the way the minor characters intervene...,Characters,1

In [142]:
test_reviews_df.shape

(132, 3)

In [143]:
test_texts = test_reviews_df["review"].tolist()
len(test_texts)

132

In [144]:
test_texts

['the cinematography is commonplace it at least does them justice',
 "The cinematography is OK', 'there are some pretty colors', 'pretty ridiculous sequences using distorted-lens effects more appropriate for a 1960s freakout movie than a costume drama",
 'the strangely annoying and unnecessary George Clooney character\', \'the characters are neurotic, needlessly offensive, and highly unlikable.\', "They are in a constant state of agonizing stress and they\'re all so irritating that I celebrated their obstacles."',
 'Alyssa Milano\', \'Tina Yothers\', "Edie McClurg was Alyssa Milano\'s mother"',
 'I loved the way the minor characters intervened just when something pivotal/climatic happened in a scene\', "just to watch Barbara Stanwyck and Co doing the \'Bunny Hug\'"',
 'list of strings with chunks where cinematography is discussed],',
 "professional filming', 'impresses immensely",
 'great Cinematography',
 'the movie as a whole just enraged both of us\', "There wasn\'t anything positive or good about this scenario"',
 'Robin Williams is actually quite good\', "the supporting performances wouldn\'t look out of place in a soft-core porno", \'every character but Sy is made of 100% cardboard',
 '"It\'s a fun and imaginative story full of magical places and people and memorable characters (both good and evil)", "Essentially, Annika (\'played\' by Barbie) has to find a way to build a \'wand of light\' to reverse the evil spells of the wizard Wenlock", "it\'s true that there were some holes in the story, or at least some logical inconsistencies", "but again one must remember the target audience, who wouldn\'t really think of such things"',
 'The film is so dark that you need a flashlight to watch it (no, not the content but the film stock itself)',
 'Uninspired lightning and camera-work are icing on the turkey film cake.',
 "The plot(such as it is) revolves around a post-apocalyptic world in which the AI robots revolted(sound familiar?) and destroyed pretty much everything, leaving a world in ruins with air so bad no one can breathe it.', 'A band of air slaves follow their leader, a mysterious wanderer who has adapted to the air outside, to go to the energy plant to destroy the Dark One.', 'The final showdown is pretty sad.",
 "photography', 'camera work ],",
 '"the most serious babe (Yeoman Barrow\'s) ever used on Star Trek"',
 '"the bile committed to celluloid known as \'Here on Earth\'", \'Klein has the delivery and facial expressions of a cardboard cutout\', \'how can this scenario turn out well?\', \'name her various body parts after the states on the eastern seaboard\', \'knee cancer from tripping',
 '"the big let-down here for me is that in having \'The Gentleman Highwayman\' there was a real opportunity for some good dialogue", \'the script was definitely lacking in punchiness and there were few belly laughs',
 '"the characters aren\'t the least bit likable", \'Sarah comes across the worst',
 'Cast was marvelous.\', "I was a bit puzzled by Siegfried and Roy\'s characters.", "Do I sense \'stereotype\' when it comes to them? Yes, they are gay. Yes, they are flamboyant."',
 'the characters go around in a haze of marijuana smoke stoning others along their way with no explanation whatsoever',
 'mixed with the truth about the condition of many Africans in South Africa made it heart wrenching\', \'good that the writer isolated Boesman and Lena from others run from their homes\', \'share fully in their triumphs and defeats\', \'conflicts they shared as they grew together and apart\', "Worth seeing when you put the movie in it\'s proper context"',
 "The film has an okay cast which includes Dax Miller, Taryn Reif, Kate Fischer, Duncan Regehr, Joel West, Matt Borlenghi, Maureen Larrazabal, Cris Vertido, Susan Africa, Archie Adamos, Rolando Santo Domingo, and Malecio Amayao.', 'The acting by the actors is fairly good.",
 'Amateur camera work aside',
 'Visuals not stunning, but good enough to ease the eye strain.',
 "disappointed in Guttenberg', 'could assemble a better covert-ops team by picking up five strangers",
 'most of the scenes look as if they were knocked up in about 5 minutes',
 "Liebman and Selby dominate the screen and communicate the intensity of their characters without flaw.', 'This film should have made them stars.",
 '"the actors were generally quite good but couldn\'t stand a chance of saving it"',
 '"I liked Del Toro\'s interpretation of Che Guevara\'s personality", \'the actor who plays Castro, Bichir, also did a great job, against all odds',
 "This movie is about Guy In Fantasy World.', 'Lovely Story",
 "i really liked the first 2 seasons.', 'i think for some reason, the producers wanted us to not like her college friends for some reason.', 'this is the absolute reverse.",
 "Story is about a high school virgin named Gary (Lawrence Monoson) who works at a pizza place as a delivery boy', 'Gary notices Karen (Diane Franklin) who is the new girl in school', 'But one night Rick brags to Gary that he nailed her at the football field and Gary becomes enraged', 'Gary helps her by taking her to his Grandmothers home and paying for her abortion', 'This film ends with a much more realistic version of how life really is",
 '"endless shots of the creepy looking school\'s exteriors that go on forever"',
 "The film is a masterpiece of poetry on the screen.', 'A very beautiful film on a controversial theme that makes humanity look up and face the reality of the outcasts in the world.",
 "the world around The Pie Hole was magnificent', 'you can almost sense the taste of the colors",
 'Where does one begin with this atrocity?\', \'The first was how did they pick the 11 competitors for this program?\', \'This was literally a talent-free talent show.\', "As badly devised as all of that was, \'The One\' had an incredible, unbelievable, fatal design flaw built into the results that made it completely laughable."',
 '"Famous was \'famous\' for their tension and release style of cartoon where the semi-main character is in terrible peril, only to be rescued by the hero at the last second.", \'This particular Casper is the only one I can remember where death actually takes a hand.\', \'But even in death, there is still a happy ending.\', "The constant in Famous Studios cartoons is that \'virtue always triumphs\'."',
 "The visuals are so good', 'the whole visuals with the black and white feeling about it', 'the totally sterile interiors were just... Just a genius perfect combination",
 'The cinematography was lousy, the movie was very dark, so I had to turn the brightness control to the maximum.',
 'I tend to see camera angles, cuts, pans, lighting, rhythms\', \'All manipulate with light, space, and sound in order to alter perception and mood\', "Matsumura\'s protagonist grows carnivorous plants, allowing for some typically Japanese cool close-up nature shots"',
 "The flawless filming stile', 'the intro scene is a classic by all means and I watched it about 20 times just for the shear atmosphere it induces to the whole film",
 'coolly, visually dazzling portrait',
 "this is the story of a young white high school girl from an upper middle class environment who is working as an escort and is discovered by her neighbor', 'the vast majority of the movie occurs in a hotel room where he hired her to come', 'through their discussion, you explore two shifting views of prostitution, depression, loneliness",
 'There are plenty of up-close shots of mouth-jabbing, tongue-cutting, and beauty queen fondling',
 'Major pieces of the movie simply appear missing, leaving it completely disjointed',
 "sensational short film explores the potential of animation through a world of playful or horrifying but always powerful images', 'extraordinary scenes and images",
 'unique qualities of black and white photography and its place in cinematic history\', "black and white photography of John Ford\'s \'Stagecoach\'"',
 '"it isn\'t nearly as beautiful as Woo can deliver", \'I particularly liked the van that flips in midair before it even comes close to touching an exploding truck\', \'cheapo LAWNMOWER MAN effects circa 1995',
 'The forward-backward motion of the storyline was well-done',
 '"The anamorphic picture element for \'A Farewell to Arms\' looks good enough, there\'s just a bit too much film grain present in certain scenes for this reviewer\'s liking.", \'Overall, colors are subtle and muted, though balanced in accordance with the DeLuxe color processing employed at this time.\', \'Some fading is evident.\', "Flesh tones don\'t appear very natural.", \'Contrast levels are a tad weak.\', \'Blacks are generally solid.\', \'Whites are almost clean.',
 '"Bruce Willis wasn\'t stretched as an actor at all", \'he did a lot of glancing to the side with that half smile of his',
 'They were indeed a crazy trio of double acts\', \'including the Gold If patter between Bud & Chesney\', "the \'Always Getting Our Man\' Mountie inserts"',
 'Filmed on location in South Africa, the audience is granted beautiful (if desolate) vistas, SA aboriginal cultures, and some nice wildlife footage to blend smoothly with the performances and storyline here.',
 'This was an uncomplicated plot, yet interesting.\', "It is a good movie to watch when you don\'t want to do a lot of thinking, just want to be told a simple story."',
 'great New York City street scenes depicting cars and shops of the era ],',
 'the camera angles',
 '"The film\'s velvety cinematography (which reminded me of Avant Garde photographer, Man Ray\'s photos of the era, which goes for some impressionistic use of light & shadow, a lot)"',
 'badly acted',
 'Jodie Foster plays her character straight out.\', "She\'s Jeanie, a high schooler who has plenty of guts, and seems to get out of any situation she\'s in.", "Scott Baio plays Brad way before Chachi on \'Happy Days\'.", \'Cherie Currie is Annie, hangs with the wrong crowd, chased by her policeman father.\', \'Jeanie and her three other friends decide to live on the wild side until they move into a rented house where a party gets totally out of hand.\', \'Annie is rescued by Jeanie and Brad all the time whenever she gets wasted.',
 "the storyline fails', 'it is a movie, without a plot",
 'women invariably have two choices, either to accept all this and take it into their own life, which is usually the case or not accept this and try to mould things to satisfy themselves',
 'The story focuses on the impact of a mentally disabled family member and its effect on the family.\', "It explores a philosophical concept on \'reality\'.", \'The film leads to thinking after viewing.',
 'The setting is gorgeous (cinematography by Gyula Pados)',
 "This movie may be the best ever if you like watching movies and laughing', 'One of the funniest parts is when Gus sharks some money off a guy with kids', 'the guy takes those kids into the forest like Hansel and Gretel",
 "the presence of Canadian cutie Chelan Simmons as the heroine.', 'John Rhys-Davies plays the captain of the ship",
 "the beautiful cinematography Polanski employs in the film helps to increase the feeling of isolation', 'the haunting images Polanski uses to convey the feeling of confusion and madness are of a supernatural beauty that makes them both frightening and attractive",
 'W. C. Fields and his frequent screen partner Alsion Skipworth appear in the second half of the film\', \'Fields seems to have been given the latitude to inject plenty of his own one-of-a-kind brand of misanthropic, surreal comedy into his part\', "Charlie Ruggles deserves special mention for his performance as the fussy banker \'Pinky\' Whinney", \'Making Burns and Allen comic annoyances to two sympathetic characters turns out to be a perfect way to fit their far-out, larger-than-life comedy characters into a real world setting',
 "no real singular plot', 'A few of the vignettes are related to each other in their character and plot lines', 'the beginning and ending scenes have a common theme too that bookends the film",
 'The moral questions raised, from murdering the sexual assaulters to the aftermath of dealing with killing a human being, remain as profound today as they did when this groundbreaking film was released.',
 '"The second episode is good, but it\'s not as good as the first Critters.", \'The third episode is a little bit boring, but lovely.\', "It\'s stupid and really, really boring.", "It\'s the worst of the series.", "I can\'t watch it again, because I felt asleep at the first watch.", "In the first 50 minutes, we can\'t see the little, furry monsters, that\'s the reason why the audience fell asleep at the beginning of the movie."',
 'Another very interesting aspect is that the project was less concerned with the racial fabric of the times but infinitely more attuned to the richness of the characters and the emotional diversity they provide to exemplify that in the final analysis it is about the choices we make and to what extent we accept responsibility for those choices.',
 'This is a frustrating story\', "why they make the sadistic mouse the \'good guy\' is beyond me"',
 'Also pay attention to the performance of Marta Belenguer, her reaction shots are incredible.',
 "the classic version of Cape Fear was extraordinarily filmed with brilliant lighting and a powerfully effective suggestive subtlety combined with a barefaced brutality', 'giving the film a cookie-cutter early 1990s look",
 "The script by producer Stephen J. Cannell, Corey Strode & Cookie Rae Brown is a complete snooze-fest for the first 40 odd minutes, nothing of any great interest happen during this period at all & is basically dull exposition as if this stuff was going to surprise anyone.', 'The story has inconsistencies like the story of the Tooth Fairy herself, it says she kills children after they give her their baby teeth so why does she go on an indiscriminate killing spree that has nothing to do with teeth?', 'What happened to her after the prologue set during 1949? Why has she come back as a ghost? Despite being a ghost of some sort she seems very human having to open doors herself & using weapons to kill people, there is no attempt to make any use of the supernatural elements except the ghostly children who are played for maximum sentiment.",
 '"grandma and grandpa and Graham Greene\'s character made sure that in the end Little Tree became a very spiritual person", "main goal as an adult was to \'catch up\' with grandma and grandpa"',
 'the full-screen framing is appalling ],',
 "there are some beautifully filmed murder sequences', 'Argento stages murder with an intricacy to eye-popping visual detail', 'the beautiful colors",
 'Grammer has a wry wit about him that really makes this movie a success.',
 "terrible photography', 'and I am not just referring to the color!",
 '"Charlotte\'s character dies in such a foolish way", "the rest of the cast, well I\'d say they simply didn\'t act very well; although the blame should be put on the poor script"',
 "the plot, characters are so weak', 'a plot with more depth",
 'The artwork and animation fits very well (note the facial expressions, lol)',
 '"Although Fitzgerald and Mason do pretty well with their parts, they can\'t really pull the film up by their work alone."',
 'To pay money to rent this as a DVD is totally inappropriate.\', "if my buddy shot this on the weekend, I\'d cheer for him, because it is quite a feat to figure out the camera controls."',
 "Surprisingly effective British drama about two very different people who find common ground', 'heartwarming and often heartbreaking tale of inner strength overcoming physical shortcomings",
 'There was some competent cinematography, even if Boll and Schwadel made mincemeat out of it',
 '"During the Civil War, there were many cases of divided loyalties; obviously, many occurred \'In the Border States\'"',
 "This movie was the biggest loser of the year.', 'This movie is headed nowhere.",
 "the direction was amazing, coupled with some brilliant camera work', 'the background score was also impressive",
 "the animation is very well done', 'the animation is smooth, detailed, and cinematically composed - not a lot of flat shots', 'The backgrounds are wonderful",
 'A group of military men/women, including a 20-something year old sexy scientist woman are left for dead by the military on an island inhabited by a giant komodo dragon.\', "The acting is pretty bad, or maybe it\'s that the special effects are so cheesy, that the acting is unbelievable."',
 'Not your typical guy film, it is in a way a coming of age comedy with two old men as oppose to two young teenagers in their prime.',
 '"The cast are rather weak and do not benefit from being shot in b&w (it\'s difficult to tell the characters apart).", \'who is an otherwise curiously appended character in that first act.',
 'the plot was all too predictable\', \'I had seen most of this in other (better) movies\', "the hints you\'re being given sound silly", \'I would rewrite the plot like this',
 'Van damme and Scott Atkins give stunning performances as the cop and the villain.',
 "Its Hollywood imitating Daytiem Soap Operas at its finest!', 'this is what I love about good comedies.",
 "interesting cinematography at times', 'wasted on the other elements",
 '"I expected this film to be a run-of-the-mill 1930\'s romance.", "It wasn\'t like that at all.", "When a blackmail job goes bad and Ruby ends up in a boarding house for \'troubled girls\', she is miserable and, thanks to the ragging her roommate gives her, begins to believe that Eddie will never come for her."',
 '"Normally, I have no problem with a movie or story with an ending that leaves you wondering to puzzle out what really happened, when it\'s done on purpose", \'this movie really feels like they got all but the last 15 minutes done, then realized they had $5 left to finish on\', \'the movie would have been better if they had simply got away, and come back with the State Police or Feds only to find that the town and the car graveyard was gone, and by all appearances had never been there',
 'half of what makes it what it is is trying to second guess what the hell they are doing on the screen because of the chiaroscuro',
 '"It\'s funny, it\'s quirky, it\'s a delightful sendup of every bad superhero cliche known to man.", "Occasional forays into junior-high humour don\'t ruin the tongue-in-cheek low-key fun."',
 "The gangsters, (led by Bryan Brown), are a menacing bunch with a humorous streak in them.', 'But this mob tickle your funny bone as well.",
 '"it\'s another example of shock horror clutching at the last straws of the pile in a desperate effort to make a poor film generate more hype", \'a crusty gore flick with limited appeal',
 '“Peter Falk gives a good performance”],',
 'no good, unclear story\', "the story doesn\'t make any sense"',
 '"one of the most beautiful Bergman movies I\'ve ever seen ],"',
 "The movie follows Jane Craig (Holly Hunter), a television news producer', 'Tom immediately charms people with humbleness', 'Another potential news anchor has been waiting for years for his on air opportunity, Aaron Altman (Albert Brooks)', 'Grunnick fails in his attempt for a romance with Jane Craig', 'Altman is angered by this fact that he knew the news and Grunnick succeeded more by getting people to like him",
 'The rotoscoping is a lot more detailed and the animation has a vibrant look to it.\', "the look has definitely gotten better since Bakshi\'s last fantasy epic.", \'the animation has almost a realistic-naturalistic style',
 'story consists of five - yes five - football matches\', "that\'s it, that\'s the plot", \'the story, such as it is ],',
 'The original benefited from a huge number of things---it was all in black and white, it had a great jazz score and it was filmed at the real locations\', \'This remake was filmed in Canada which I guess doubles okay for Kansas.\', "It\'s very well filmed and acted."',

In [145]:
test_labels = test_reviews_df["aspect_encoded"].tolist()
len(test_labels)

132

### Task 19

Let's pre-process (tokenize, encode, pad, and truncate) the text sequences in the testing dataset using the previous functions:
- `encode_text` - uses the vocabulary to tokenize and encode text into token IDs
- `pad_or_truncate` - pads or truncates the encoded text to a specified maximum sequence length

Be sure to use the same maximum sequence length we used for the training dataset.

Save the pre-processed test sequences to the variable `padded_text_seqs_test`.

In [146]:
padded_text_seqs_test =   [pad_or_truncate(encode_text(text, vocab), MAX_SEQ_LENGTH) for text in test_texts]

In [147]:
padded_text_seqs_test

[[2,
  91,
  6,
  0,
  9,
  34,
  440,
  125,
  170,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  91,
  6,
  0,
  48,
  20,
  35,
  209,
  0,
  209,
  449,
  0,
  0,
  0,
  736,
  129,
  54,
  0,
  17,
  3,
  0,
  0,
  19,
  78,
  3,
  0,
  189,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  0,
  853,
  4,
  0,
  754,
  0,
  53,
  2,
  38,
  20,
  0,
  0,
  0,
  4,
  871,
  0,
  24,
  20,
  8,
  3,
  321,
  0,
  5,
  0,
  0,
  4,
  24,
  272,
  32,
  57,
  0,
  11,
  14,
  0,
  50,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  0,
  0,
  0,
  350,
  0,
  15,
  0,
  0,
  10,
  480,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [14,
  205,
  2,
  84,
  2,
  0,
  38,
  0,
  46,
  118,
  200,
  0,
  0,
  0,
  8,
  3,
  169,
  46,
  7,
  156,
  0,
  0,
  4,
  0,
  380,
  2,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  5,
  0,
  18,
  0,
  155,
  91,
  6,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [872,
  252,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [52,
  91,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  19,
  13,
  3,
  233,
  46,
  0,
  207,
  5,
  212,
  48,
  0,
  27,
  191,
  0,
  45,
  37,
  43,
  12,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  0,
  6,
  223,
  214,
  37,
  2,
  923,
  243,
  0,
  27,
  76,
  44,
  5,
  0,
  8,
  3,
  0,
  0,
  0,
  361,
  53,
  30,
  0,
  6,
  105,
  5,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [9,
  10,
  3,
  174,
  4,
  804,
  25,
  181,
  5,
  0,
  612,
  4,
  86,
  4,
  0,
  38,
  207,
  37,
  4,
  337,
  0,
  0,
  166,
  40,
  0,
  41,
  7,
  126,
  3,
  84,
  7,
  625,
  3,
  0,
  5,
  0,
  7,
  0,
  2,
  337,
  0,
  5,
  2,
  0,
  0,
  9,
  10,
  232,
  11,
  48,
  60,
  35,
  390,
  8,
  2,
  25,
  45,
  34,
  440,
  35,
  0,
  0,
  30,
  341,
  31,
  513,
  0,
  2,
  0,
  231,
  47,
  0,
  27,
  55,
  176,
  5,
  282,
  354,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  16,
  6,
  57,
  270,
  11,
  39,
  0,
  3,
  0,
  7,
  156,
  9,
  104,
  23,
  2,
  743,
  30,
  2,
  16,
  411,
  751,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  0,
  4,
  56,
  68,
  20,
  0,
  22,
  2,
  0,
  16,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  62,
  282,
  13,
  9,
  6,
  0,
  190,
  3,
  655,
  0,
  139,
  8,
  89,
  2,
  0,
  0,
  0,
  0,
  0,
  4,
  0,
  209,
  66,
  193,
  487,
  3,
  139,
  8,
  0,
  18,
  451,
  57,
  73,
  104,
  31,
  61,
  0,
  9,
  3,
  879,
  5,
  451,
  0,
  538,
  50,
  0,
  3,
  709,
  0,
  47,
  41,
  0,
  7,
  2,
  451,
  0,
  7,
  179,
  7,
  2,
  0,
  0,
  7,
  0,
  2,
  270,
  31,
  2,
  0,
  0,
  6,
  209,
  741,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [172,
  56,
  68,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  69,
  0,
  0,
  0,
  0,
  10,
  102,
  546,
  22,
  333,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  0,
  0,
  7,
  0,
  632,
  13,
  123,
  22,
  0,
  0,
  41,
  2,
  0,
  4,
  0,
  0,
  5,
  3,
  0,
  0,
  88,
  61,
  12,
  0,
  353,
  44,
  99,
  442,
  51,
  0,
  0,
  297,
  192,
  2,
  0,
  22,
  2,
  771,
  0,
  0,
  0,
  75,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  178,
  862,
  332,
  123,
  17,
  116,
  6,
  11,
  8,
  344,
  2,
  0,
  0,
  48,
  15,
  3,
  180,
  0,
  17,
  35,
  37,
  408,
  2,
  183,
  15,
  0,
  0,
  8,
  0,
  4,
  48,
  60,
  399,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  38,
  466,
  27,
  2,
  440,
  299,
  577,
  0,
  385,
  0,
  2,
  360,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [135,
  15,
  0,
  14,
  15,
  3,
  299,
  0,
  40,
  0,
  4,
  0,
  10,
  38,
  64,
  14,
  167,
  0,
  118,
  9,
  385,
  7,
  170,
  473,
  24,
  20,
  493,
  473,
  24,
  20,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  38,
  179,
  190,
  8,
  3,
  0,
  5,
  0,
  0,
  0,
  0,
  563,
  50,
  84,
  18,
  104,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  18,
  2,
  0,
  43,
  2,
  0,
  5,
  94,
  0,
  8,
  0,
  0,
  105,
  9,
  689,
  0,
  37,
  11,
  2,
  0,
  0,
  0,
  4,
  0,
  75,
  0,
  482,
  75,
  50,
  0,
  0,
  926,
  8,
  50,
  0,
  4,
  0,
  0,
  24,
  0,
  13,
  24,
  0,
  433,
  4,
  0,
  816,
  0,
  118,
  39,
  920,
  2,
  19,
  8,
  9,
  10,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  16,
  41,
  33,
  0,
  135,
  89,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  842,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  0,
  0,
  2,
  80,
  40,
  2,
  95,
  6,
  941,
  37,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  56,
  68,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [250,
  23,
  287,
  30,
  37,
  173,
  7,
  0,
  2,
  367,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  8,
  0,
  93,
  0,
  3,
  124,
  0,
  0,
  0,
  40,
  0,
  63,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [69,
  5,
  2,
  77,
  76,
  13,
  133,
  24,
  60,
  0,
  63,
  8,
  43,
  0,
  855,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [0,
  4,
  0,
  0,
  2,
  248,
  4,
  0,
  2,
  0,
  5,
  50,
  38,
  318,
  0,
  12,
  16,
  0,
  36,
  105,
  170,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [2,
  95,
  60,
  0,
  214,
  37,
  30,
  719,
  27,
  0,
  3,
  952,
  5,
  0,
  9,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [14,
  0,
  0,
  0,
  10,
  0,
  5,
  0,
  0,
  10,
  0,
  2,
  186,
  47,
  196,
  0,
  0,
  58,
  153,
  3,
  52,
  149,
  452,
  32,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 [12,
  19,
  6,
  43,
  121,
  8,
  0,
  139,
  745,
  25,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,

### Task 20

Next, let's convert the pre-processed test sequences into PyTorch tensors:
- create the input tensor `X_tensor_test` by converting the padded/truncated test sequences
- create the label tensor `y_tensor_test` by converting the testing labels (be sure to specify thet datatype `torch.long`


Using the PyTorch utility module `torch.utils.data`, let's organize the testing input and label tensors into a single dataset object and an iterable that will allow us to load the testing data in batches:
- create the variable `` using the `TensorDataset` utility class to organize the input tensor and label tensor into a single dataset object
- create the variable `test_dataloader` using the `DataLoader` utility class to create an iterable that loads the `test_dataset` in batches of `8` (be sure to set `shuffle` to `False`)

In [148]:
X_tensor_test = torch.tensor(padded_text_seqs_test)
y_tensor_test = torch.tensor(test_labels, dtype=torch.long)

In [149]:
X_tensor_test

tensor([[  2,  91,   6,  ...,   1,   1,   1],
        [  2,  91,   6,  ...,   1,   1,   1],
        [  2,   0, 853,  ...,   1,   1,   1],
        ...,
        [794,   4,   0,  ...,   1,   1,   1],
        [  2,  25,  15,  ...,   1,   1,   1],
        [  2,   0,   6,  ...,   1,   1,   1]])

In [150]:
y_tensor_test

tensor([0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 2, 1, 1, 1, 2, 1, 0,
        0, 1, 0, 1, 1, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 2, 0, 0,
        0, 2, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 2, 1, 2, 0, 2, 1, 0, 1, 2, 2, 2, 2,
        2, 1, 0, 2, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 1, 2,
        1, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 0, 1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 1, 2,
        1, 2, 0, 0, 2, 1, 1, 1, 1, 0, 2, 1])

In [151]:
test_dataset = TensorDataset(X_tensor_test,y_tensor_test)
test_dataloader =  DataLoader(test_dataset,  batch_size=8, shuffle=False)

### Task 21

Let's generate predictions from the trained neural network on the reviews in the testing dataset!

A. Create the function `get_predictions_and_probabilities` that takes in the trained model and testing dataloader as input.

B. Within the function:
- set the model to evaluation mode
- initialize the following empty lists:
    - `all_probs` - stores all of the predicted probabilities for the testing dataset
    - `all_labels` - stores all of the predicted labels for the testing dataset

- using `with torch.no_grad()`, loop through each batch in the testing dataloader and:
    -  generate outputs from the forward pass
    -  use the **softmax** function to generate predicted probabilities (be sure to add the probabilities to the `all_probs` list using `extend()`
    -  use the **argmax** function to select the class label with the highest probabilities (be sure to add the labels to the `all_labels` list using `extend()`
- the function should return the predicted probabilities `all_probs` and predicted labels `all_labels`

C. Apply the `get_predictions_and_probabilities` to generate predictions. Save the predicted probabilities to the variable `pred_probs` and predicted labels to the variable `pred_labels`.

In [172]:
import torch.nn.functional as F

def get_predictions_and_probabilities(model, test_dataloader):
    model.eval()
    all_probs = []
    all_labels = []

    with torch.no_grad():
        for test_batch, test_label in test_dataloader:
            output = model(test_batch)
            batch_probs = F.softmax(output, dim=1)
            batch_labels = torch.argmax(output, dim=1)

            all_probs.extend(batch_probs.cpu().numpy())
            all_labels.extend(batch_labels.cpu().numpy())
    return np.array(all_labels), np.array(all_probs)

In [177]:
pred_labels, pred_probs = get_predictions_and_probabilities(text_classifier_nn, test_dataloader)

In [179]:
pred_probs, pred_labels

(array([[9.70694959e-01, 2.11658701e-02, 8.13921355e-03],
        [9.29370940e-01, 3.54670472e-02, 3.51619795e-02],
        [6.25694383e-06, 9.98845220e-01, 1.14846870e-03],
        [8.70773569e-02, 9.08262491e-01, 4.66017006e-03],
        [1.07080489e-02, 9.87059474e-01, 2.23246333e-03],
        [9.98969316e-01, 6.39146718e-04, 3.91549460e-04],
        [9.58654225e-01, 2.15760358e-02, 1.97697468e-02],
        [9.85679090e-01, 1.34249553e-02, 8.95911537e-04],
        [6.89036533e-05, 3.18680238e-03, 9.96744275e-01],
        [2.72073457e-03, 9.96189952e-01, 1.08932320e-03],
        [7.12642167e-09, 1.79300623e-04, 9.99820769e-01],
        [7.43148290e-03, 2.29630228e-02, 9.69605505e-01],
        [9.99718845e-01, 2.15055334e-04, 6.59898360e-05],
        [9.59403478e-05, 2.81158660e-04, 9.99622822e-01],
        [9.99972105e-01, 1.28163747e-05, 1.50660499e-05],
        [8.90988529e-01, 6.03147708e-02, 4.86966819e-02],
        [5.22864093e-06, 9.75746274e-01, 2.42484659e-02],
        [3.74624942e-04, 2.88881697e-02, 9.70737219e-01],
        [5.85055735e-04, 9.88624334e-01, 1.07906759e-02],
        [1.05247109e-05, 9.96828973e-01, 3.16041987e-03],
        [3.30791995e-03, 3.98098916e-01, 5.98593175e-01],
        [6.67013956e-05, 4.73446399e-01, 5.26486874e-01],
        [1.69127986e-07, 9.99995470e-01, 4.37682729e-06],
        [9.99314070e-01, 5.20750124e-04, 1.65198464e-04],
        [9.99206007e-01, 7.15741713e-04, 7.82659772e-05],
        [2.20543379e-03, 9.93196130e-01, 4.59850486e-03],
        [8.50927293e-01, 1.47891566e-01, 1.18111214e-03],
        [1.68884406e-03, 9.70126450e-01, 2.81847119e-02],
        [3.18191767e-01, 6.38083756e-01, 4.37245034e-02],
        [4.71234525e-04, 9.99438107e-01, 9.06316054e-05],
        [3.32898535e-02, 5.90298958e-02, 9.07680213e-01],
        [7.75685254e-03, 8.88282835e-01, 1.03960276e-01],
        [5.16064631e-07, 9.75724936e-01, 2.42745485e-02],
        [9.91161346e-01, 2.85315909e-03, 5.98551380e-03],
        [9.91427839e-01, 7.75049499e-04, 7.79709406e-03],
        [4.77475256e-01, 2.93952256e-01, 2.28572488e-01],
        [2.67989293e-07, 1.91079509e-02, 9.80891764e-01],
        [5.53240125e-06, 9.03258741e-01, 9.67358053e-02],
        [9.86255050e-01, 4.41420925e-05, 1.37008801e-02],
        [9.97864902e-01, 1.75543828e-03, 3.79712583e-04],
        [9.99988198e-01, 9.88510874e-06, 1.93020196e-06],
        [9.95512456e-02, 7.79522525e-05, 9.00370777e-01],
        [8.79884005e-01, 9.30353403e-02, 2.70806514e-02],
        [1.43630155e-06, 4.77740094e-02, 9.52224553e-01],
        [9.94677186e-01, 4.02263412e-03, 1.30021549e-03],
        [5.30996639e-03, 6.76357653e-03, 9.87926483e-01],
        [9.99966860e-01, 7.01737417e-06, 2.61336481e-05],
        [9.99998450e-01, 2.24800246e-07, 1.34347010e-06],
        [4.80150571e-03, 8.30521509e-02, 9.12146389e-01],
        [9.49335098e-01, 1.30366441e-02, 3.76282372e-02],
        [2.02633757e-02, 9.77496386e-01, 2.24017166e-03],
        [1.34804219e-01, 8.00845265e-01, 6.43505007e-02],
        [7.47630020e-06, 9.99804914e-01, 1.87655882e-04],
        [9.99878168e-01, 7.76090892e-05, 4.42267810e-05],
        [2.89402487e-06, 2.23647430e-06, 9.99994874e-01],
        [8.48738492e-01, 1.47248343e-01, 4.01321892e-03],
        [9.99760091e-01, 9.68001186e-05, 1.43107973e-04],
        [9.98481691e-01, 7.64310185e-04, 7.53988570e-04],
        [6.08335853e-01, 1.33990496e-01, 2.57673711e-01],
        [2.88618074e-10, 9.99996901e-01, 3.10801761e-06],
        [1.46129081e-04, 3.80042737e-04, 9.99473870e-01],
        [4.22674239e-05, 2.86395159e-02, 9.71318185e-01],
        [4.28387970e-02, 3.92679907e-02, 9.17893231e-01],
        [9.94271278e-01, 5.49513334e-03, 2.33578990e-04],
        [3.11762124e-05, 9.35395777e-01, 6.45729378e-02],
        [8.91674217e-03, 9.90863085e-01, 2.20181697e-04],
        [9.99981523e-01, 9.82837810e-06, 8.75678506e-06],
        [2.48441445e-08, 9.82773423e-01, 1.72266085e-02],
        [3.30260559e-06, 2.60769611e-05, 9.99970675e-01],
        [1.25318451e-03, 8.45274329e-01, 1.53472483e-01],
        [1.27440334e-08, 1.04482588e-05, 9.99989510e-01],
        [1.51921908e-04, 1.62522076e-03, 9.98222888e-01],
        [3.06093134e-05, 4.23014015e-02, 9.57667947e-01],
        [9.98712420e-01, 1.26927835e-03, 1.83638658e-05],
        [9.99901414e-01, 5.37468122e-06, 9.31598188e-05],
        [3.22368570e-13, 6.88900769e-01, 3.11099231e-01],
        [1.64534813e-05, 9.78004992e-01, 2.19785832e-02],
        [3.46950412e-01, 6.03818297e-01, 4.92313243e-02],
        [9.99740064e-01, 2.62308586e-05, 2.33748724e-04],
        [1.98407797e-04, 5.25830686e-02, 9.47218537e-01],
        [9.98773396e-01, 1.01287325e-03, 2.13683728e-04],
        [1.95367480e-04, 7.48947680e-01, 2.50856996e-01],
        [1.23904523e-04, 4.93567530e-03, 9.94940400e-01],
        [9.32622075e-01, 6.48665205e-02, 2.51140282e-03],
        [3.94761376e-02, 2.67586440e-01, 6.92937374e-01],
        [1.12726748e-01, 3.86518419e-01, 5.00754833e-01],
        [4.43883007e-03, 9.89977479e-01, 5.58361690e-03],
        [9.63852525e-01, 2.11979449e-02, 1.49495676e-02],
        [9.96082425e-01, 2.65437970e-03, 1.26321334e-03],
        [3.80080603e-02, 1.46695316e-01, 8.15296590e-01],
        [9.99964356e-01, 8.84871679e-06, 2.68426174e-05],
        [9.99967933e-01, 2.59723256e-05, 6.12144549e-06],
        [5.58792954e-06, 9.84934330e-01, 1.50599685e-02],
        [3.08082854e-05, 5.58301713e-03, 9.94386196e-01],
        [7.39818133e-05, 9.96999264e-01, 2.92688725e-03],
        [1.27346948e-05, 5.18549932e-04, 9.99468744e-01],
        [5.16741097e-01, 4.63596731e-01, 1.96621306e-02],
        [7.45660067e-02, 6.53686762e-01, 2.71747172e-01],
        [9.98630702e-01, 6.56530377e-04, 7.12786161e-04],
        [9.35010830e-05, 2.63481028e-02, 9.73558366e-01],
        [5.99188268e-11, 4.97404486e-04, 9.99502540e-01],
        [9.78631750e-02, 2.64936358e-01, 6.37200415e-01],
        [2.24506039e-05, 1.38892059e-03, 9.98588622e-01],
        [5.01481211e-03, 9.87808049e-01, 7.17708655e-03],
        [4.15408552e-01, 2.92217883e-04, 5.84299266e-01],
        [9.31756556e-01, 5.94152510e-02, 8.82821530e-03],
        [4.23095953e-05, 2.60087429e-04, 9.99697685e-01],
        [9.61232841e-01, 7.33704586e-03, 3.14300731e-02],
        [3.80671366e-07, 9.97469068e-01, 2.53055524e-03],
        [9.75831866e-01, 1.93074881e-03, 2.22373698e-02],
        [3.46677638e-07, 3.65773144e-06, 9.99995947e-01],
        [9.70142424e-01, 2.52817063e-06, 2.98551004e-02],
        [9.85444725e-01, 8.88547627e-04, 1.36667043e-02],
        [7.83344905e-04, 4.08005377e-04, 9.98808622e-01],
        [8.04652035e-01, 1.56228572e-01, 3.91194113e-02],
        [1.49166135e-06, 1.75190522e-04, 9.99823391e-01],
        [9.99982476e-01, 4.63595597e-06, 1.29130503e-05],
        [5.62867615e-03, 3.80757192e-05, 9.94333267e-01],
        [4.80941526e-05, 9.94930208e-01, 5.02169691e-03],
        [5.33487320e-01, 1.87848117e-02, 4.47727889e-01],
        [2.39463611e-06, 9.99905109e-01, 9.24400229e-05],
        [3.14905316e-01, 6.11739635e-01, 7.33550787e-02],
        [7.75143683e-01, 2.03818843e-01, 2.10375134e-02],
        [9.27470982e-01, 4.11787108e-02, 3.13503370e-02],
        [7.20391273e-02, 4.31712531e-02, 8.84789586e-01],
        [7.69190198e-11, 9.99976277e-01, 2.37487966e-05],
        [7.11390972e-02, 1.55922368e-01, 7.72938550e-01],
        [1.16503658e-03, 9.92237985e-01, 6.59702113e-03],
        [1.12612464e-01, 5.80954790e-01, 3.06432873e-01],
        [9.99866486e-01, 1.10276334e-04, 2.32686943e-05],
        [5.74226647e-07, 8.37759289e-05, 9.99915600e-01],
        [3.68132204e-01, 5.99600196e-01, 3.22675742e-02]], dtype=float32),
 array([0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 2, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2,
        1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 2,
        0, 2, 0, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 1,
        0, 1, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 2, 0, 2, 2, 1, 0,
        0, 2, 0, 0, 1, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 0, 1, 0,
        2, 0, 0, 2, 0, 2, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2, 1, 1, 0, 2, 1]))

### Task 22

Let's evaluate the model's predictions (`pred_labels`) with the true labels (`test_labels`).

A. Generate a **confusion matrix** to count the number of true negatives (TN), false positives (FP), false negatives (FN), and true positives (TP). Save the confusion matrix to the variable `conf_matrix`.

B. Generate a **classification report** to calculate the accuracy, precision, recall, and F1-score metrics for each label. Save the classification report to the variable `report`.

Print the confusion matrix and classification report.

In [183]:
from sklearn.metrics import confusion_matrix, classification_report
conf_matrix = confusion_matrix(test_labels, pred_labels)
print(conf_matrix)

[[41  2  6]
 [ 5 28  5]
 [ 5 10 30]]

In [182]:
report = classification_report(test_labels, pred_labels)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.84      0.82        49
           1       0.70      0.74      0.72        38
           2       0.73      0.67      0.70        45

    accuracy                           0.75       132
   macro avg       0.75      0.75      0.75       132
weighted avg       0.75      0.75      0.75       132

<details><summary style="display:list-item; font-size:16px; color:blue;">How well does the simple neural network perform when classifying movie reviews?</summary>

    
**Confusion Matrix**

We can interpret the confusion matrix by this structure:
    
```py
    [[TP0 FN0  FN0]
     [FN1 TP1  FN1]
     [FN2 FN2  TP2]]
```

Each row corresponds to the TPs and FNs for each review aspect: 
    
- row 1 corresponds to the TPs and FNs for Cinematography reviews (label 0)
    - 27 Cinematography reviews were correctly classified as Cinematography reviews (label 0)
    - 18 Cinematography reviews were incorrectly classified as Character reviews (label 1)
    - 4 Cinematography reviews were incorrectly classified as Story reviews (label 2)
- row 2 corresponds to the TPs and FNs for Character reviews (label 1)
    - 35 Character reviews were correctly classified as Character reviews (label 1)
    - 1 Character review was incorrectly classified as a Cinematography review (label 0)
    - 2 Character reviews were incorrectly classified as Story reviews (label 2)
- row 3 corresponds to the TPs and FNs for Story reviews (label 2)
    - 28 Story reviews were correctly classified as Story reviews (label 2)
    - 2 Story review was incorrectly classified as a Cinematography review (label 0)
    - 15 Story reviews were incorrectly classified as Character reviews (label 1)    

**Classification Report**

When classifying movie reviews, the simple neural network (with an embedding layer) had an overall accuracy of 68%, which is decent but not too great. 
    
For Cinematography reviews (label 0):
- the model has a high precision score of 90%, meaning that when it classified a review as a Cinematography review, it was right 90% of the time
- however, the model has a low recall score of 55%, meaning that it could only identify 55% of all Cinematography reviews, which suggests that it is overpredicting 
    
For Character reviews (label 1):
- the model has a low precision score of 51%, meaning that when it classified a review as a Character review, it was right 51% of the time (pretty much a 50/50 coin flip)
- however, the model has a high recall score of 92%, meaning that it successfully identified 92% of all Character reviews
- this suggests that the model rarely misses a Character review, but seems to misclassify the other review aspects often
    
For Story reviews (label 2):
- the model has a decent precision score of 82%, meaning that when it classified a review as a Story review, it was right 82% of the time
- however, the model has a low recall score of 62%, meaning that it could only identify 62% of all Story reviews
    
Overall, the model performs moderately well in classifying movie review aspects, but there is definitely room for improvement.

## Task Group - Fine-tuning a TinyBERT Transformer

Let's now train a more advanced BERT transformer language model! Specifically, let's fine-tune a TinyBERT model to classify movie reviews!

### Task 23

Load the pre-trained BERT model using the `transformers` library from Hugging Face.

Due to memory and hardware constraints, we won't be able to use the full pre-trained BERT model that contains 12 layers and 110 million parameters. Instead, we'll use a distilled, smaller version of BERT called **TinyBERT** that contains 4 layers and 14.5 million parameters developed by Huawei Noah's Ark Lab (https://huggingface.co/huawei-noah).

A. First, save the TinyBERT model name `'huawei-noah/TinyBERT_General_4L_312D'` as a string to the variable `model_name`.

B. Download and load the TinyBERT tokenizer from the `BertTokenizer` module and save the tokenizer to the variable `tinybert_tokenizer`.

C. Download and load the TinyBERT models (weights) with the `BertForSequenceClassification` module. Be sure to specify `num_labels=` with the correct number of class labels (# of movie aspects). Save the TinyBERT model to the variable `text_classifier_tinybert`.

### Task 24

Before fine-tuning the TinyBERT, let's **freeze** and **unfreeze** the following layers:

- first, freeze all of the parameters in the pre-trained TinyBERT
- second, unfreeze the classification layer added on top of the pre-trained model
- third, unfreeze the encoder layer specified at `layer[3]`

### Task 25

Let's pre-process the training text reviews (`train_texts`) with the TinyBERT tokenizer:
- specify a maximum sequence length of `124` and save the value to the variable `MAX_SEQ_LENGTH_TINYBERT`
- create the tensor `X_train` that contains the tokenized training text tokenized by the TinyBERT tokenizer:
    - the sequences have a maximum length of **128** tokens
    - the sequences are **padded**
    - the sequences are **truncated**
    - the padded and truncated sequences are returned as PyTorch tensors
- create the tensor `y_train` that contains the corresponding training labels in `train_labels` converted to a PyTorch tensor (be sure to specify the `torch.long` datatype)

Using the PyTorch utility module `torch.utils.data`, let's organize the training input and label tensors into a single dataset object and an iterable that will allow us to load the training data in batches:
- create the variable `train_dataset` using the `TensorDataset` utility class to organize the input tensor `X_train` and label tensor `y_train` into a single dataset object (be sure to specify the attention mask in the input tensor created by the TinyBERT tokenizer)
- create the variable `train_dataloader` using the `DataLoader` utility class to create an iterable that loads the `train_dataset` in batches of `16` (be sure to set `shuffle` to `True`)

### Task 26

Next, let's initialize the optimizer and loss function to fine-tune our TinyBERT model (`text_classifier_tinybert`).

A. Initialize the Adam optimizer with **weight decay** with a learning rate of `0.0025`. Ensure that only the unfrozen layers are optimized during training. Save the optimizer to the variable `optimizer`.

B. Initialize the cross-entropy loss function. Save the loss function to the variable `criterion`.

### Task 27

Let's create a training loop to fine-tune the TinyBERT model for `10` epochs!

A. Set the value of `10` to the variable `num_epochs`.

B. Create a training loop first loops through each epoch where in each epoch:
- set the TinyBERT model to training mode
- initialize the empty variable `total_loss` with `0.0` to keep track of the total loss per epoch
- create a nested loop that loops through each batch (be sure to specify the batch's attention mask) in the training dataloader where for each batch:
    1. reset the gradients
    2. apply the forward pass to the training batch (be sure to pass the current batch's attention mask)
    3. extract the logits from the forward pass output
    4. calculate the cross-entropy loss
    5. update the `total_loss`
    6. backpropagate the loss through the network
    7. adjust the weights and biases

### Task 28

Now that the TinyBERT model is fine-tuned, let's evaluate how the transformer performs on the movie reviews in the testing set and compare its performance with the simple neural network from before!

Pre-process the testing dataset into the following PyTorch tensors:

- create the tensor `X_test` using the TinyBERT tokenizer to tokenize and testing dataset and save the pre-processed tensor to the variable `X_test`:
    - the maximum sequence length should be same as the length used during fine-tuning the TinyBERT
    - apply padding and truncating
    - return the tokenized text as a PyTorch tensor
- create the tensor `y_test` that contains the testing labels `test_labels` as a PyTorch tensor (be sure to specify the `torch.long` datatype).

Using the PyTorch utility module `torch.utils.data`, let's organize the training input and label tensors into a single dataset object and an iterable that will allow us to load the training data in batches:
- create the variable `test_dataset` using the `TensorDataset` utility class to organize the input tensor `X_test` and label tensor `y_test` into a single dataset object (be sure to specify the attention mask in the input tensor created by the TinyBERT tokenizer)
- create the variable `test_dataloader` using the `DataLoader` utility class to create an iterable that loads the `test_dataset` in batches of `8` (be sure to set `shuffle` to `False`)

### Task 29

Next, let's generate predictions from the fine-tuned TinyBERT!

A. Set the fine-tuned TinyBERT model to evaluation mode.

B. Initialize the following empty lists:
- `pred_probs` - stores the predicted probabilities for the reviews in the testing dataset
- `pred_labels` - stores the predicted labels for the reviews in the testing dataset

C. Within `with torch.no_grad()`:
- loop through each batch in the testing dataloader (be sure to specify the attention masks)
- apply the forward pass to each batch
- obtain the logits from the outputs from the forward pass
-  use the **softmax** function to generate predicted probabilities (be sure to add the probabilities to the `pred_probs` list using `extend()`
-  use the **argmax** function to select the class label with the highest probabilities (be sure to add the labels to the `pred_labels` list using `extend()`

### Task 30

Let's see how well our fine-tuned TinyBERT model classifies movie reviews!

Evaluate the TinyBERT model's predictions (`pred_labels`) with the true labels (`test_labels`) with the following:

A. Generate a **confusion matrix** to count the number of true negatives (TN), false positives (FP), false negatives (FN), and true positives (TP). Save the confusion matrix to the variable `conf_matrix`.

B. Generate a **classification report** to calculate the accuracy, precision, recall, and F1-score metrics for each label. Save the classification report to the variable `report`.

Print the confusion matrix and classification report.

How does the fine-tuned TinyBERT model performance compare to the simple neural network?

<details><summary style="display:list-item; font-size:16px; color:blue;">How does the fine-tuned TinyBERT model performance compare to the simple neural network?</summary>
   
**Confusion Matrix**

We can interpret the confusion matrix by this structure:
    
```py
    [[TP0 FN0  FN0]
     [FN1 TP1  FN1]
     [FN2 FN2  TP2]]
```

Each row corresponds to the TPs and FNs for each review aspect: 
    
- row 1 corresponds to the TPs and FNs for Cinematography reviews (label 0)
    - 49 Cinematography reviews were correctly classified as Cinematography reviews (label 0)
    - 0 Cinematography reviews were incorrectly classified as Character reviews (label 1)
    - 0 Cinematography reviews were incorrectly classified as Story reviews (label 2)
- row 2 corresponds to the TPs and FNs for Character reviews (label 1)
    - 38 Character reviews were correctly classified as Character reviews (label 1)
    - 0 Character review was incorrectly classified as a Cinematography review (label 0)
    - 0 Character reviews were incorrectly classified as Story reviews (label 2)
- row 3 corresponds to the TPs and FNs for Story reviews (label 2)
    - 35 Story reviews were correctly classified as Story reviews (label 2)
    - 8 Story review was incorrectly classified as a Cinematography review (label 0)
    - 2 Story reviews were incorrectly classified as Character reviews (label 1)    

**Classification Report**

When classifying movie reviews, the fine-tuned TinyBERT achieved an overall accuracy of 92%, which outperformed the simple neural network that had an overall accuracy of 68%. 
    
For Cinematography reviews (label 0):
- the model has a high precision score of 86%, meaning that when it classified a review as a Cinematography review, it was right 86% of the time
- the model has a perfect recall score of 100%, meaning that it correctly identified all Cinematography reviews
    
For Character reviews (label 1):
- the model has a high precision score of 95%, meaning that when it classified a review as a Character review, it was right 95% of the time
- the model has a perfect recall score of 100%, meaning that it correctly identified all Character reviews
    
For Story reviews (label 2):
- the model has a perfect precision score of 100%, meaning that when it classified a review as a Story review, it was right 100% of the time
- the model has a decent recall score of 78%, meaning that it identified 78% of all Story reviews

    
The macro and weighted average F1 Score of 92% tell us that the model performs well across all label aspects.
    
Overall, the model performs exceptionally well in classifying movie review aspects, confirming that fine-tuning a TinyBERT model outperforms a simple neural network for this text classification task!

Note: The Jupyter Notebook kernel may crash or be unresponsive after fine-tuning the TinyBERT model. Be sure to save your work every so often to avoid losing any work you've done so far! Feel free to restart the kernel and re-run the cells.

That's the end of our project on building text classification models to classify different aspects of movie reviews! There's definitely a lot of room for improvement and we encourage you to use your skills to explore different techniques to enhance the language models.

Here are some areas for improvement:
- increase the maximum sequence length
- increase the training batch sizes
- freeze/unfreeze different layers in the TinyBERT architecture
- increase the number of training epochs
- try different optimizers and learning rates
- try a different transformer model
- increase the size of training dataset ([Full Hugging Face Dataset](https://huggingface.co/datasets/Lowerated/lm6-movies-reviews-aspects))

You might want to consider building and training larger language models on your own device or cloud platform with greater memory.

Happy coding!